import { describe, expect, test } from "bun:test";
import { SQL } from "bun";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;
const TEST_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(TEST_DIR, "..", "..");
const FIXTURE_SQL = readFileSync(join(TEST_DIR, "fixtures", "audit_portfolio.sql"), "utf-8");
const EXPECTED = JSON.parse(readFileSync(join(REPO_ROOT, "scripts", "audit", "expected.json"), "utf-8")) as AuditExpected;

type NumericRecord = Record<string, number | string>;

type AuditExpected = {
  daily_returns: {
    count: number;
    checkpoints: Array<NumericRecord & { date: string }>;
  };
  performance: NumericRecord;
  mwr: number;
  status: NumericRecord;
  realized_gains: {
    total: number;
    rows: Array<NumericRecord & { sell_date: string; asset: string }>;
  };
};

function tempTableDDL() {
  return {
    transactions: `
      CREATE TEMP TABLE transactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date DATE NOT NULL,
        asset VARCHAR NOT NULL,
        action VARCHAR NOT NULL,
        quantity DOUBLE PRECISION NOT NULL,
        asset_type VARCHAR,
        price DOUBLE PRECISION,
        currency VARCHAR,
        fees DOUBLE PRECISION,
        fee_currency VARCHAR,
        exchange VARCHAR,
        data_source VARCHAR,
        account VARCHAR,
        exchange_group_id TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
      ) ON COMMIT DROP
    `,
    prices: `
      CREATE TEMP TABLE prices (
        date DATE NOT NULL,
        ticker VARCHAR NOT NULL,
        price DOUBLE PRECISION NOT NULL,
        PRIMARY KEY (date, ticker)
      ) ON COMMIT DROP
    `,
    dailyReturns: `
      CREATE TEMP TABLE daily_returns (
        date DATE PRIMARY KEY,
        portfolio_value DOUBLE PRECISION NOT NULL,
        portfolio_daily_return DOUBLE PRECISION,
        investment_return DOUBLE PRECISION,
        cash_flow_impact DOUBLE PRECISION,
        adjusted_base DOUBLE PRECISION
      ) ON COMMIT DROP
    `,
  };
}

async function createTempTables(tx: any) {
  const ddl = tempTableDDL();
  await tx.unsafe(ddl.transactions);
  await tx.unsafe(ddl.prices);
  await tx.unsafe(ddl.dailyReturns);
}

function dateKey(value: unknown): string {
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  return String(value).slice(0, 10);
}

function expectClose(actual: unknown, expected: number, tolerance = 1e-6) {
  const got = Number(actual);
  expect(Number.isFinite(got)).toBe(true);
  expect(Math.abs(got - expected)).toBeLessThanOrEqual(tolerance);
}

function expectNullableClose(actual: unknown, expected: number | string, tolerance = 1e-6) {
  if (typeof expected === "string") {
    expect(dateKey(actual)).toBe(expected);
    return;
  }
  expectClose(actual, expected, tolerance);
}

MAYBE_SKIP("integration: hard performance audit fixture (#226)", () => {
  test(
    "fixture expected values match daily_returns, performance, MWR, status, and realized gains",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await createTempTables(tx);
          await tx.unsafe(FIXTURE_SQL);
          await tx.unsafe(`SELECT refresh_daily_returns_sql()`);

          const [countRow] = await tx.unsafe(
            `SELECT COUNT(*)::INTEGER AS count FROM daily_returns WHERE date <= $1`,
            [EXPECTED.performance.end_date],
          ) as any[];
          expect(Number(countRow.count)).toBe(EXPECTED.daily_returns.count);

          const dates = EXPECTED.daily_returns.checkpoints.map((row) => row.date);
          const placeholders = dates.map((_, i) => `$${i + 1}`).join(", ");
          const checkpointRows = await tx.unsafe(
            `SELECT date, portfolio_value, portfolio_daily_return, investment_return, cash_flow_impact
             FROM daily_returns
             WHERE date IN (${placeholders})
             ORDER BY date`,
            dates,
          ) as any[];
          expect(checkpointRows.length).toBe(EXPECTED.daily_returns.checkpoints.length);
          for (let i = 0; i < checkpointRows.length; i += 1) {
            const actual = checkpointRows[i];
            const expected = EXPECTED.daily_returns.checkpoints[i];
            expect(dateKey(actual.date)).toBe(expected.date);
            expectClose(actual.portfolio_value, Number(expected.portfolio_value), 1e-6);
            expectClose(actual.portfolio_daily_return, Number(expected.portfolio_daily_return), 1e-6);
            expectClose(actual.investment_return, Number(expected.investment_return), 1e-6);
            expectClose(actual.cash_flow_impact, Number(expected.cash_flow_impact), 1e-6);
          }

          const [perf] = await tx.unsafe(
            `SELECT * FROM portfolio_performance_sql($1, 'SPY', NULL, 0.02, 0.025)`,
            [EXPECTED.performance.end_date],
          ) as any[];
          for (const [metric, expected] of Object.entries(EXPECTED.performance)) {
            expectNullableClose(perf[metric], expected, metric.includes("ratio") || metric === "beta" ? 1e-8 : 1e-6);
          }
          expect(Number(perf.total_return_pct)).not.toBeCloseTo(Number(perf.time_weighted_return_pct), 4);

          const [mwr] = await tx.unsafe(
            `SELECT portfolio_mwr_sql($1) AS mwr`,
            [EXPECTED.performance.end_date],
          ) as any[];
          expectClose(mwr.mwr, EXPECTED.mwr, 1e-6);

          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [EXPECTED.performance.end_date],
          ) as any[];
          for (const [metric, expected] of Object.entries(EXPECTED.status)) {
            expectNullableClose(status[metric], expected, 1e-6);
          }

          const realizedRows = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, $1, NULL)`,
            [EXPECTED.performance.end_date],
          ) as any[];
          expect(realizedRows.length).toBe(EXPECTED.realized_gains.rows.length);
          const realizedTotal = realizedRows.reduce((sum: number, row: any) => sum + Number(row.realized_gain), 0);
          expectClose(realizedTotal, EXPECTED.realized_gains.total, 1e-6);
          expect(dateKey(realizedRows[0].sell_date)).toBe(EXPECTED.realized_gains.rows[0].sell_date);
          expect(realizedRows[0].asset).toBe(EXPECTED.realized_gains.rows[0].asset);
          expectClose(realizedRows[0].realized_gain, Number(EXPECTED.realized_gains.rows[0].realized_gain), 1e-6);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 20000 },
  );

  test(
    "realized-gains from_date preserves pre-period FIFO lots for in-period sells",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await createTempTables(tx);
          await tx.unsafe(FIXTURE_SQL);

          const rows = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql('2025-01-01'::DATE, $1, NULL)`,
            [EXPECTED.performance.end_date],
          ) as any[];

          expect(rows.length).toBe(1);
          expect(dateKey(rows[0].matched_buy_date)).toBe("2024-01-02");
          expectClose(rows[0].realized_gain, EXPECTED.realized_gains.total, 1e-6);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "empty portfolio returns a zero-row performance result without throwing",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await createTempTables(tx);
          const [perf] = await tx.unsafe(`SELECT * FROM portfolio_performance_sql('2026-01-05'::DATE)`) as any[];
          expect(Number(perf.total_days)).toBe(0);
          expect(perf.start_date).toBeNull();
          expect(Number(perf.total_gain)).toBe(0);
          expect(Number(perf.time_weighted_return_pct)).toBe(0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "single-day daily_returns input suppresses annualized metrics that require elapsed time",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await createTempTables(tx);
          await tx.unsafe(`
            INSERT INTO daily_returns (date, portfolio_value, portfolio_daily_return, investment_return, cash_flow_impact, adjusted_base)
            VALUES ('2026-01-05', 1000, 0, 0, 0, 1000)
          `);
          const [perf] = await tx.unsafe(`SELECT * FROM portfolio_performance_sql('2026-01-05'::DATE)`) as any[];
          expect(Number(perf.total_days)).toBe(1);
          expect(Number(perf.cagr)).toBe(0);
          expect(Number(perf.total_return_pct)).toBe(0);
          expect(Number(perf.std_dev)).toBe(0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "zero-variance investment returns produce zero volatility and zero Sharpe",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await createTempTables(tx);
          await tx.unsafe(`
            INSERT INTO daily_returns (date, portfolio_value, portfolio_daily_return, investment_return, cash_flow_impact, adjusted_base)
            SELECT
              '2026-01-01'::DATE + (n - 1),
              1000.0 * POWER(1.005, n - 1),
              0.5,
              0.5,
              0,
              1000.0
            FROM generate_series(1, 10) AS gs(n)
          `);
          const [perf] = await tx.unsafe(`SELECT * FROM portfolio_performance_sql('2026-01-10'::DATE)`) as any[];
          expect(Number(perf.std_dev)).toBe(0);
          expect(Number(perf.hist_volatility)).toBe(0);
          expect(Number(perf.sharpe_ratio)).toBe(0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "inflation above nominal return produces negative real return fields",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await createTempTables(tx);
          await tx.unsafe(`
            INSERT INTO daily_returns (date, portfolio_value, portfolio_daily_return, investment_return, cash_flow_impact, adjusted_base)
            VALUES
              ('2025-01-01', 1000, 0, 0, 0, 1000),
              ('2026-01-01', 1000, 0, 0, 0, 1000)
          `);
          const [perf] = await tx.unsafe(
            `SELECT * FROM portfolio_performance_sql('2026-01-01'::DATE, 'SPY', NULL, 0.02, 0.025)`,
          ) as any[];
          expect(Number(perf.real_cagr)).toBeLessThan(0);
          expect(Number(perf.real_total_return_pct)).toBeLessThan(0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "gaps in daily_returns are handled by date joins, not array-position benchmark alignment",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await createTempTables(tx);
          await tx.unsafe(`
            INSERT INTO daily_returns (date, portfolio_value, portfolio_daily_return, investment_return, cash_flow_impact, adjusted_base)
            VALUES
              ('2026-01-01', 1000, 0, 0, 0, 1000),
              ('2026-01-03', 1100, 10, 10, 0, 1000),
              ('2026-01-10', 1210, 10, 10, 0, 1000)
          `);
          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('SPY', '2026-01-01', 100),
              ('SPY', '2026-01-10', 110)
          `);
          const [perf] = await tx.unsafe(`SELECT * FROM portfolio_performance_sql('2026-01-10'::DATE)`) as any[];
          expect(Number(perf.total_days)).toBe(3);
          expect(Number(perf.time_weighted_return_pct)).toBeCloseTo(21, 6);
          expect(Number(perf.spy_twr_pct)).toBeCloseTo(10, 6);
          expect(Number.isFinite(Number(perf.tracking_error))).toBe(true);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );
});
