import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

MAYBE_SKIP("integration: cross-engine consistency guard (#87)", () => {
  test(
    "status.portfolio_value == summary.portfolio_value_usd == SUM(allocation.value_usd) == SUM(non-cash valued)+SUM(cash usd_value)",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-01-15', 'USD', 'DEPOSIT', 10000, NULL, 0,  'USD', NULL),
              ('2026-01-16', 'AAPL', 'BUY',     10,    150, 2.50, 'USD', NULL),
              ('2026-01-17', 'SAP.DE', 'BUY',    5,    120, 15,   'EUR', NULL),
              ('2026-01-18', 'NVDA', 'BUY',      5,    500, 0.0001, 'USD', 'BTC'),
              ('2026-01-19', 'GBPUSD=X', 'DEPOSIT', 5000, NULL, 0, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL',     '2026-01-16', 150),
              ('AAPL',     '2026-01-17', 155),
              ('AAPL',     '2026-01-18', 160),
              ('AAPL',     '2026-01-19', 165),
              ('SAP.DE',   '2026-01-17', 120),
              ('SAP.DE',   '2026-01-18', 125),
              ('SAP.DE',   '2026-01-19', 130),
              ('NVDA',     '2026-01-18', 500),
              ('NVDA',     '2026-01-19', 520),
              ('BTC-USD',  '2026-01-18', 50000),
              ('BTC-USD',  '2026-01-19', 51000),
              ('EURUSD=X', '2026-01-17', 1.10),
              ('EURUSD=X', '2026-01-18', 1.11),
              ('EURUSD=X', '2026-01-19', 1.12),
              ('GBPUSD=X', '2026-01-19', 1.34)
          `);

          const asOf = "2026-01-19";

          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [asOf],
          ) as any[];

          const [summary] = await tx.unsafe(
            `SELECT * FROM portfolio_summary_sql($1)`,
            [asOf],
          ) as any[];

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1)`,
            [asOf],
          ) as any[];

          const cash = await tx.unsafe(
            `SELECT * FROM portfolio_cash_sql($1)`,
            [asOf],
          ) as any[];

          const allocTotal = allocation.reduce(
            (sum: number, r: any) => sum + Number(r.value_usd),
            0,
          );
          const cashTotal = cash.reduce(
            (sum: number, r: any) => sum + Number(r.usd_value),
            0,
          );
          const nonCashTotal = allocation
            .filter((r: any) => r.asset_type !== "cash_base" && r.asset_type !== "cash_fx")
            .reduce((sum: number, r: any) => sum + Number(r.value_usd), 0);

          const portfolioValue = Number(status.portfolio_value);
          const summaryValue = Number(summary.portfolio_value_usd);

          const tol = 0.02;

          expect(status.as_of_date).toBe(asOf);
          expect(summary.as_of_date).toBe(asOf);

          expect(portfolioValue).toBeCloseTo(summaryValue, 2);
          expect(portfolioValue).toBeCloseTo(allocTotal, 2);
          expect(portfolioValue).toBeCloseTo(nonCashTotal + cashTotal, 2);

          expect(portfolioValue).toBeGreaterThan(0);

          expect(Math.abs(portfolioValue - summaryValue)).toBeLessThan(tol);
          expect(Math.abs(portfolioValue - allocTotal)).toBeLessThan(tol);
          expect(Math.abs(portfolioValue - (nonCashTotal + cashTotal))).toBeLessThan(tol);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "#223 SII consistency: period_returns.SII == portfolio_performance_sql.time_weighted_return_pct",
    async () => {
      const tsql = new SQL(DB_URL!, { max: 1 });
      try {
        await tsql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE daily_returns (
              date DATE PRIMARY KEY,
              portfolio_value DOUBLE PRECISION NOT NULL,
              portfolio_daily_return DOUBLE PRECISION,
              investment_return DOUBLE PRECISION,
              cash_flow_impact DOUBLE PRECISION,
              adjusted_base DOUBLE PRECISION
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO daily_returns (date, portfolio_value, investment_return, portfolio_daily_return, cash_flow_impact, adjusted_base)
            SELECT
              '2025-01-01'::DATE + (gs.n - 1) AS date,
              10000.0 * POWER(1.001, gs.n - 1) AS portfolio_value,
              0.1 AS investment_return,
              0.1 AS portfolio_daily_return,
              0.0 AS cash_flow_impact,
              10000.0 * POWER(1.001, gs.n - 2) AS adjusted_base
            FROM generate_series(1, 500) AS gs(n)
          `);

          const asOf = "2026-05-15";

          const [perf] = await tx.unsafe(
            `SELECT * FROM portfolio_performance_sql($1)`,
            [asOf],
          ) as any[];

          const periodRows = await tx.unsafe(
            `SELECT * FROM portfolio_period_returns_sql($1)`,
            [asOf],
          ) as any[];

          const rollingRows = await tx.unsafe(
            `SELECT * FROM portfolio_rolling_returns_sql($1, 12)`,
            [asOf],
          ) as any[];

          const periodMap: Record<string, number> = {};
          for (const pr of periodRows) {
            periodMap[pr.window] = Number(pr.return_pct);
          }

          const twrFromPerf = Number(perf.time_weighted_return_pct);
          const siiFromPeriod = periodMap["SII"];

          expect(twrFromPerf).toBeGreaterThan(0);
          expect(siiFromPeriod).toBeGreaterThan(0);
          expect(Math.abs(twrFromPerf - siiFromPeriod)).toBeLessThan(1e-6);

          expect(periodMap["YTD"]).toBeGreaterThan(0);
          expect(Number.isFinite(periodMap["YTD"])).toBe(true);
          expect(periodMap["1Y"]).toBeGreaterThan(0);
          expect(Number.isFinite(periodMap["1Y"])).toBe(true);

          expect(rollingRows.length).toBeGreaterThan(0);
          for (const rr of rollingRows) {
            expect(Number.isFinite(Number(rr.return_pct))).toBe(true);
            expect(String(rr.date)).toMatch(/^\d{4}-\d{2}-\d{2}$/);
          }
        });
      } finally {
        await tsql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "#223 rolling_12m_returns: ordered, non-empty series for >12-month fixture",
    async () => {
      const tsql = new SQL(DB_URL!, { max: 1 });
      try {
        await tsql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE daily_returns (
              date DATE PRIMARY KEY,
              portfolio_value DOUBLE PRECISION NOT NULL,
              portfolio_daily_return DOUBLE PRECISION,
              investment_return DOUBLE PRECISION,
              cash_flow_impact DOUBLE PRECISION,
              adjusted_base DOUBLE PRECISION
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO daily_returns (date, portfolio_value, investment_return, portfolio_daily_return, cash_flow_impact, adjusted_base)
            SELECT
              '2025-01-01'::DATE + (gs.n - 1) AS date,
              10000.0 * POWER(1.001, gs.n - 1) AS portfolio_value,
              CASE WHEN random() < 0.5 THEN 0.05 ELSE 0.15 END AS investment_return,
              CASE WHEN random() < 0.5 THEN 0.05 ELSE 0.15 END AS portfolio_daily_return,
              0.0 AS cash_flow_impact,
              10000.0 * POWER(1.001, gs.n - 2) AS adjusted_base
            FROM generate_series(1, 500) AS gs(n)
          `);

          const asOf = "2026-05-15";

          const rollingRows = await tx.unsafe(
            `SELECT * FROM portfolio_rolling_returns_sql($1, 12)`,
            [asOf],
          ) as any[];

          expect(rollingRows.length).toBeGreaterThan(0);

          let prevDate = "";
          for (const rr of rollingRows) {
            const rd = String(rr.date);
            const val = Number(rr.return_pct);
            expect(rd).toMatch(/^\d{4}-\d{2}-\d{2}$/);
            expect(Number.isFinite(val)).toBe(true);
            if (prevDate) {
              expect(rd > prevDate).toBe(true);
            }
            prevDate = rd;
          }
        });
      } finally {
        await tsql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "DELIBERATE DRIFT CHECK: portfolio_value from status and allocation align to the cent",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-01-01', 'USD', 'DEPOSIT', 15000, NULL, 0,  'USD', NULL),
              ('2026-01-02', 'VTI',   'BUY',  50,   200, 5,   'USD', NULL),
              ('2026-01-03', 'VXUS',  'BUY',  30,    55, 2.50,'USD', NULL),
              ('2026-01-04', 'USD', 'WITHDRAW', 500, NULL, 0, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('VTI',  '2026-01-02', 200),
              ('VTI',  '2026-01-03', 202),
              ('VTI',  '2026-01-04', 205),
              ('VXUS', '2026-01-03', 55),
              ('VXUS', '2026-01-04', 56)
          `);

          const asOf = "2026-01-04";

          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [asOf],
          ) as any[];

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1)`,
            [asOf],
          ) as any[];

          const [summary] = await tx.unsafe(
            `SELECT * FROM portfolio_summary_sql($1)`,
            [asOf],
          ) as any[];

          // Hand-calculated:
          // Start cash: 15000
          // BUY VTI: 50*200 + 5 = 10005
          // BUY VXUS: 30*55 + 2.50 = 1652.50
          // WITHDRAW: 500
          // Remaining cash: 15000 - 10005 - 1652.50 - 500 = 2842.50
          //
          // VTI market: 50 * 205 = 10250
          // VXUS market: 30 * 56 = 1680
          //
          // Total portfolio: 2842.50 + 10250 + 1680 = 14772.50

          const expectedTotal = 14772.50;
          const tolerance = 0.02;

          expect(Number(status.portfolio_value)).toBeCloseTo(expectedTotal, 2);

          const allocTotal = allocation.reduce(
            (sum: number, r: any) => sum + Number(r.value_usd),
            0,
          );

          expect(allocTotal).toBeCloseTo(expectedTotal, 2);
          expect(Number(summary.portfolio_value_usd)).toBeCloseTo(expectedTotal, 2);

          expect(Math.abs(Number(status.portfolio_value) - allocTotal)).toBeLessThan(tolerance);
          expect(
            Math.abs(Number(status.portfolio_value) - Number(summary.portfolio_value_usd)),
          ).toBeLessThan(tolerance);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );
});
