import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const maybeDescribe = DB_URL ? describe : describe.skip;

type Tx = {
  unsafe: (sql: string, params?: unknown[]) => Promise<Record<string, unknown>[]>;
};

function num(val: unknown): number {
  const n = Number(val);
  if (!Number.isFinite(n)) {
    throw new Error(`expected finite number, got ${String(val)}`);
  }
  return n;
}

async function createFixtureTables(tx: Tx): Promise<void> {
  await tx.unsafe(`
    CREATE TEMP TABLE transactions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date DATE NOT NULL,
      asset VARCHAR NOT NULL,
      action VARCHAR NOT NULL,
      quantity DOUBLE PRECISION NOT NULL,
      asset_type VARCHAR,
      price DOUBLE PRECISION,
      currency VARCHAR,
      fees DOUBLE PRECISION,
      fee_currency VARCHAR,
      exchange VARCHAR,
      data_source VARCHAR,
      account VARCHAR,
      exchange_group_id TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP
    ) ON COMMIT DROP
  `);

  await tx.unsafe(`
    CREATE TEMP TABLE prices (
      date DATE NOT NULL,
      ticker VARCHAR NOT NULL,
      price DOUBLE PRECISION NOT NULL,
      PRIMARY KEY (date, ticker)
    ) ON COMMIT DROP
  `);
}

async function seedPrice(tx: Tx, ticker: string, date: string, price: number): Promise<void> {
  await tx.unsafe(
    `INSERT INTO prices (date, ticker, price) VALUES ($1, $2, $3)`,
    [date, ticker, price],
  );
}

maybeDescribe("crypto reward and wrap/unwrap integration", () => {
  test(
    "staking reward fixture: zero-basis BTC reward keeps cash/deposits unchanged and realizes full proceeds on sell",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: Tx) => {
          await createFixtureTables(tx);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, asset_type, price, currency, fees, fee_currency, exchange, data_source, account)
            VALUES
              ('2026-01-01', 'USD', 'DEPOSIT', 1000, 'cash_base', NULL, 'USD', NULL, NULL, 'Bank', '', NULL),
              ('2026-01-02', 'BTC-USD', 'STAKING_REWARD', 0.00017429, 'crypto', NULL, 'USD', NULL, NULL, 'Binance Earn', '', NULL),
              ('2026-01-10', 'BTC-USD', 'SELL', 0.00017429, 'crypto', 60000, 'USD', 0, NULL, 'Binance', '', NULL)
          `);

          await seedPrice(tx, "BTC-USD", "2026-01-02", 60000);
          await seedPrice(tx, "BTC-USD", "2026-01-10", 60000);

          const beforeSellStatus = await tx.unsafe(`SELECT * FROM portfolio_status_sql('2026-01-02')`);
          const beforeSell = beforeSellStatus[0] as Record<string, unknown>;
          expect(num(beforeSell.deposits)).toBeCloseTo(1000, 6);
          expect(num(beforeSell.withdrawals)).toBeCloseTo(0, 6);
          expect(num(beforeSell.cost_basis)).toBeCloseTo(0, 6);
          expect(num(beforeSell.realized_gain)).toBeCloseTo(0, 6);
          expect(num(beforeSell.unrealized_gain)).toBeCloseTo(10.46, 2);

          const cashRows = await tx.unsafe(`SELECT * FROM portfolio_cash_sql('2026-01-02')`);
          const cashTotal = cashRows.reduce((sum, row) => sum + num(row.usd_value), 0);
          expect(cashTotal).toBeCloseTo(1000, 6);

          const allocationRows = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql('2026-01-02') WHERE asset = 'BTC-USD'`,
          );
          expect(allocationRows).toHaveLength(1);
          expect(num(allocationRows[0].net_quantity)).toBeCloseTo(0.00017429, 8);
          expect(num(allocationRows[0].value_usd)).toBeCloseTo(10.4574, 4);

          const incomeRows = await tx.unsafe(
            `SELECT * FROM portfolio_income_sql('2026-01-10', NULL, NULL)`,
          );
          expect(incomeRows).toHaveLength(0);

          const gainsRows = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, '2026-01-10', 'BTC-USD')`,
          );
          expect(gainsRows).toHaveLength(1);
          const gainRow = gainsRows[0] as Record<string, unknown>;
          expect(num(gainRow.proceeds_usd)).toBeCloseTo(10.4574, 4);
          expect(num(gainRow.cost_basis_usd)).toBeCloseTo(0, 6);
          expect(num(gainRow.realized_gain)).toBeCloseTo(10.4574, 4);
          expect(num(gainRow.holding_days)).toBe(8);

          const afterSellStatus = await tx.unsafe(`SELECT * FROM portfolio_status_sql('2026-01-10')`);
          const afterSell = afterSellStatus[0] as Record<string, unknown>;
          expect(num(afterSell.deposits)).toBeCloseTo(1000, 6);
          expect(num(afterSell.cost_basis)).toBeCloseTo(0, 6);
          expect(num(afterSell.realized_gain)).toBeCloseTo(10.46, 2);
          expect(num(afterSell.unrealized_gain)).toBeCloseTo(0, 6);
          expect(num(afterSell.portfolio_value)).toBeCloseTo(1010.4574, 4);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "wrap fixture: ETH basis transfers to WBETH, then sell realizes gain off transferred basis",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: Tx) => {
          await createFixtureTables(tx);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, asset_type, price, currency, fees, fee_currency, exchange, data_source, account, exchange_group_id)
            VALUES
              ('2026-02-01', 'USD', 'DEPOSIT', 1000, 'cash_base', NULL, 'USD', NULL, NULL, 'Bank', '', NULL, NULL),
              ('2026-02-01', 'ETH-USD', 'BUY', 2, 'crypto', 100, 'USD', 0, NULL, 'Coinbase', '', NULL, NULL),
              ('2026-02-05', 'ETH-USD', 'WRAP', -1, 'crypto', NULL, '', NULL, NULL, 'Coinbase', '', NULL, 'wrap-1'),
              ('2026-02-05', 'WBETH-USD', 'UNWRAP', 1.05, 'crypto', NULL, '', NULL, NULL, 'Coinbase', '', NULL, 'wrap-1'),
              ('2026-02-10', 'WBETH-USD', 'SELL', 1.05, 'crypto', 120, 'USD', 0, NULL, 'Coinbase', '', NULL, NULL)
          `);

          await seedPrice(tx, "ETH-USD", "2026-02-01", 100);
          await seedPrice(tx, "ETH-USD", "2026-02-10", 100);
          await seedPrice(tx, "WBETH-USD", "2026-02-10", 120);

          const gainsRows = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, '2026-02-10', 'WBETH-USD')`,
          );
          expect(gainsRows).toHaveLength(1);
          const gainRow = gainsRows[0] as Record<string, unknown>;
          expect(num(gainRow.proceeds_usd)).toBeCloseTo(126, 6);
          expect(num(gainRow.cost_basis_usd)).toBeCloseTo(100, 6);
          expect(num(gainRow.realized_gain)).toBeCloseTo(26, 6);

          const statusRows = await tx.unsafe(`SELECT * FROM portfolio_status_sql('2026-02-10')`);
          const status = statusRows[0] as Record<string, unknown>;
          expect(num(status.deposits)).toBeCloseTo(1000, 6);
          expect(num(status.cost_basis)).toBeCloseTo(100, 6);
          expect(num(status.realized_gain)).toBeCloseTo(26, 6);
          expect(num(status.unrealized_gain)).toBeCloseTo(0, 6);
          expect(num(status.portfolio_value)).toBeCloseTo(1026, 6);

          const allocationRows = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql('2026-02-10') WHERE asset IN ('ETH-USD', 'WBETH-USD') ORDER BY asset`,
          );
          expect(allocationRows).toHaveLength(1);
          expect(allocationRows[0].asset).toBe("ETH-USD");
          expect(num(allocationRows[0].net_quantity)).toBeCloseTo(1, 6);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "unwrap fixture: WBETH basis transfers back to ETH, then sell realizes gain off transferred basis",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: Tx) => {
          await createFixtureTables(tx);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, asset_type, price, currency, fees, fee_currency, exchange, data_source, account, exchange_group_id)
            VALUES
              ('2026-03-01', 'USD', 'DEPOSIT', 1000, 'cash_base', NULL, 'USD', NULL, NULL, 'Bank', '', NULL, NULL),
              ('2026-03-01', 'WBETH-USD', 'BUY', 1.05, 'crypto', 100, 'USD', 0, NULL, 'Coinbase', '', NULL, NULL),
              ('2026-03-05', 'WBETH-USD', 'WRAP', -1.05, 'crypto', NULL, '', NULL, NULL, 'Coinbase', '', NULL, 'unwrap-1'),
              ('2026-03-05', 'ETH-USD', 'UNWRAP', 1, 'crypto', NULL, '', NULL, NULL, 'Coinbase', '', NULL, 'unwrap-1'),
              ('2026-03-10', 'ETH-USD', 'SELL', 1, 'crypto', 120, 'USD', 0, NULL, 'Coinbase', '', NULL, NULL)
          `);

          await seedPrice(tx, "WBETH-USD", "2026-03-01", 100);
          await seedPrice(tx, "ETH-USD", "2026-03-10", 120);

          const gainsRows = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, '2026-03-10', 'ETH-USD')`,
          );
          expect(gainsRows).toHaveLength(1);
          const gainRow = gainsRows[0] as Record<string, unknown>;
          expect(num(gainRow.proceeds_usd)).toBeCloseTo(120, 6);
          expect(num(gainRow.cost_basis_usd)).toBeCloseTo(105, 6);
          expect(num(gainRow.realized_gain)).toBeCloseTo(15, 6);

          const statusRows = await tx.unsafe(`SELECT * FROM portfolio_status_sql('2026-03-10')`);
          const status = statusRows[0] as Record<string, unknown>;
          expect(num(status.deposits)).toBeCloseTo(1000, 6);
          expect(num(status.cost_basis)).toBeCloseTo(0, 6);
          expect(num(status.realized_gain)).toBeCloseTo(15, 6);
          expect(num(status.unrealized_gain)).toBeCloseTo(0, 6);
          expect(num(status.portfolio_value)).toBeCloseTo(1015, 6);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );
});
