import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

const TEMP_TABLES = `
  CREATE TEMP TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    asset VARCHAR NOT NULL,
    action VARCHAR NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    asset_type VARCHAR,
    price DOUBLE PRECISION,
    currency VARCHAR,
    fees DOUBLE PRECISION,
    fee_currency VARCHAR,
    exchange VARCHAR,
    data_source VARCHAR,
    account VARCHAR,
    exchange_group_id TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
  ) ON COMMIT DROP;

  CREATE TEMP TABLE prices (
    date DATE NOT NULL,
    ticker VARCHAR NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (date, ticker)
  ) ON COMMIT DROP;
`;

MAYBE_SKIP("integration: currency_exposure (#215)", () => {
  test(
    "hand-calc fixture: USD stock + EUR stock + USD cash + EUR cash",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-01-15', 'USD',     'DEPOSIT',  50000, NULL, 0,   'USD', NULL, 'bank'),
              ('2026-01-16', 'EUR',     'DEPOSIT',  5000,  NULL, 0,   'USD', NULL, 'bank'),
              ('2026-01-17', 'AAPL',    'BUY',     100,   200,  10,   'USD', NULL, 'nasdaq'),
              ('2026-01-18', 'SAP.DE',  'BUY',      50,   100,  5,    'EUR', NULL, 'xetra'),
              ('2026-01-19', 'GBP',     'DEPOSIT',  2000,  NULL, 0,   'USD', NULL, 'bank')
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL',     '2026-01-17', 200),
              ('AAPL',     '2026-01-18', 205),
              ('AAPL',     '2026-01-19', 210),
              ('SAP.DE',   '2026-01-18', 100),
              ('SAP.DE',   '2026-01-19', 105),
              ('EURUSD=X', '2026-01-18', 1.10),
              ('EURUSD=X', '2026-01-19', 1.12),
              ('GBPUSD=X', '2026-01-19', 1.30)
          `);

          const asOf = "2026-01-19";

          const exposure = await tx.unsafe(
            `SELECT * FROM portfolio_currency_exposure_sql($1) ORDER BY usd_value DESC`,
            [asOf],
          ) as any[];

          // Hand-calculated as-of 2026-01-19:
          // USD cash: 50000 - (100*200 + 10) = 50000 - 20010 = 29990
          // EUR cash: 5000 - (50*100 + 5) = 5000 - 5005 = -5 EUR
          // EUR cash USD value: -5 * 1.12 = -5.60
          // GBP cash: 2000 * 1.30 = 2600 USD
          //
          // AAPL holdings: 100 * 210 = 21000
          // SAP.DE holdings: 50 * 105 * 1.12 = 5880
          //
          // USD exposure: 29990 (cash) + 21000 (AAPL holdings) = 50990
          // EUR exposure: -5.60 (cash) + 5880 (SAP.DE holdings) = 5874.40
          // GBP exposure: 2600 (cash) + 0 (holdings) = 2600
          //
          // Portfolio total: 50990 + 5874.40 + 2600 = 59464.40

          expect(exposure.length).toBe(3);

          const usdRow = exposure.find((r: any) => r.currency === "USD");
          const eurRow = exposure.find((r: any) => r.currency === "EUR");
          const gbpRow = exposure.find((r: any) => r.currency === "GBP");

          expect(usdRow).toBeDefined();
          expect(eurRow).toBeDefined();
          expect(gbpRow).toBeDefined();

          // USD
          expect(Number(usdRow.usd_value)).toBeCloseTo(50990, 1);
          expect(Number(usdRow.holdings_usd)).toBeCloseTo(21000, 1);
          expect(Number(usdRow.cash_usd)).toBeCloseTo(29990, 1);

          // EUR
          expect(Number(eurRow.usd_value)).toBeCloseTo(5874.40, 1);
          expect(Number(eurRow.holdings_usd)).toBeCloseTo(5880, 1);
          expect(Number(eurRow.cash_usd)).toBeCloseTo(-5.60, 1);

          // GBP
          expect(Number(gbpRow.usd_value)).toBeCloseTo(2600, 1);
          expect(Number(gbpRow.holdings_usd)).toBeCloseTo(0, 1);
          expect(Number(gbpRow.cash_usd)).toBeCloseTo(2600, 1);

          // pct sums to ~100
          const pctSum = exposure.reduce((s: number, r: any) => s + Number(r.pct), 0);
          expect(pctSum).toBeCloseTo(100, 1);

          // Σ usd_value == portfolio_value
          const usdSum = exposure.reduce((s: number, r: any) => s + Number(r.usd_value), 0);
          expect(usdSum).toBeCloseTo(Number(exposure[0].portfolio_value), 1);

          // portfolio_value matches allocation total
          const allocation = await tx.unsafe(
            `SELECT SUM(value_usd) AS total FROM portfolio_allocation_sql($1)`,
            [asOf],
          ) as any[];
          expect(usdSum).toBeCloseTo(Number(allocation[0].total), 1);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "USD-only portfolio returns single row at 100%",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-01-01', 'USD',  'DEPOSIT', 10000, NULL, 0, 'USD', NULL, 'bank'),
              ('2026-01-02', 'AAPL', 'BUY',     10,    150,  5, 'USD', NULL, 'nasdaq')
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-01-02', 150),
              ('AAPL', '2026-01-03', 155)
          `);

          const asOf = "2026-01-03";

          const exposure = await tx.unsafe(
            `SELECT * FROM portfolio_currency_exposure_sql($1) ORDER BY usd_value DESC`,
            [asOf],
          ) as any[];

          expect(exposure.length).toBe(1);

          const row = exposure[0];
          expect(row.currency).toBe("USD");
          expect(Number(row.pct)).toBeCloseTo(100, 1);
          expect(Number(row.usd_value)).toBeCloseTo(Number(row.portfolio_value), 1);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "empty portfolio returns 0 rows",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          const asOf = "2026-01-01";

          const exposure = await tx.unsafe(
            `SELECT * FROM portfolio_currency_exposure_sql($1) ORDER BY usd_value DESC`,
            [asOf],
          ) as any[];

          expect(exposure.length).toBe(0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );
});
