import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

function tempTableDDL() {
  return {
    transactions: `
      CREATE TEMP TABLE transactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date DATE NOT NULL,
        asset VARCHAR NOT NULL,
        action VARCHAR NOT NULL,
        quantity DOUBLE PRECISION NOT NULL,
        asset_type VARCHAR,
        price DOUBLE PRECISION,
        currency VARCHAR,
        fees DOUBLE PRECISION,
        fee_currency VARCHAR,
        exchange VARCHAR,
        data_source VARCHAR,
        account VARCHAR,
        exchange_group_id TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
      ) ON COMMIT DROP
    `,
    prices: `
      CREATE TEMP TABLE prices (
        date DATE NOT NULL,
        ticker VARCHAR NOT NULL,
        price DOUBLE PRECISION NOT NULL,
        PRIMARY KEY (date, ticker)
      ) ON COMMIT DROP
    `,
  };
}

// ── Fixture A: two perfectly-correlated assets ──
// AAPL: 50→55→60.5→66.55  (% returns: 0.1, 0.1, 0.1)
// GOOGL: 100→110→121→133.1 (% returns: 0.1, 0.1, 0.1)
// Equal dollar allocation → w_A = w_B = 0.5.
// HHI = (0.5² + 0.5²) × 10000 = 5000
// effective_holdings = 1 / 0.5 = 2.0
// ρ = 1.0
// CWHHI = (0.25 + 0.25 + 2×0.5×0.5×1.0) × 10000 = 10000
function fixturePerfectCorr(): { tx: string; prices: string; asOf: string } {
  return {
    tx: `
      INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, exchange)
      VALUES
        ('2026-01-01', 'USD',   'DEPOSIT', 1000, NULL, 0, 'USD', 'bank'),
        ('2026-01-01', 'AAPL',  'BUY',     10,   50,   0, 'USD', 'IBKR'),
        ('2026-01-01', 'GOOGL', 'BUY',     5,    100,  0, 'USD', 'IBKR')
    `,
    prices: `
      INSERT INTO prices (ticker, date, price)
      VALUES
        ('AAPL',  '2026-01-01', 50.0),
        ('AAPL',  '2026-01-02', 55.0),
        ('AAPL',  '2026-01-03', 60.5),
        ('AAPL',  '2026-01-04', 66.55),
        ('GOOGL', '2026-01-01', 100.0),
        ('GOOGL', '2026-01-02', 110.0),
        ('GOOGL', '2026-01-03', 121.0),
        ('GOOGL', '2026-01-04', 133.1)
    `,
    asOf: "2026-01-04",
  };
}

// ── Fixture B: perfectly negative correlation ──
// TESTA: 100→110→99→108.9  (% returns: 0.1, -0.1, 0.1)
// TESTB: 200→180→198→178.2 (% returns: -0.1, 0.1, -0.1)
// Weights use as-of MARKET value (portfolio_allocation_sql), so quantities are
// chosen so the two positions end at EQUAL value (1.8×108.9 == 1.1×178.2 == 196.02)
// and the deposit is fully invested (no leftover cash holding). Only then do the
// weights equal 0.5/0.5 and CWHHI collapse to 0 for a perfectly hedged pair.
// HHI = 5000 ; effective_holdings = 2.0
// CWHHI = (0.25 + 0.25 + 2×0.5×0.5×(-1.0)) × 10000 = 0
function fixtureNegCorr(): { tx: string; prices: string; asOf: string } {
  return {
    tx: `
      INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, exchange)
      VALUES
        ('2026-01-01', 'USD',   'DEPOSIT', 400, NULL, 0, 'USD', 'bank'),
        ('2026-01-01', 'TESTA', 'BUY',     1.8,  100,  0, 'USD', 'IBKR'),
        ('2026-01-01', 'TESTB', 'BUY',     1.1,  200,  0, 'USD', 'IBKR')
    `,
    prices: `
      INSERT INTO prices (ticker, date, price)
      VALUES
        ('TESTA', '2026-01-01', 100.0),
        ('TESTA', '2026-01-02', 110.0),
        ('TESTA', '2026-01-03', 99.0),
        ('TESTA', '2026-01-04', 108.9),
        ('TESTB', '2026-01-01', 200.0),
        ('TESTB', '2026-01-02', 180.0),
        ('TESTB', '2026-01-03', 198.0),
        ('TESTB', '2026-01-04', 178.2)
    `,
    asOf: "2026-01-04",
  };
}

// ── Fixture C: zero cross-correlation ──
// ONEX: 100→110→99→108.9→98.01  (% returns: 0.1, -0.1, 0.1, -0.1)
// TWOX: 500→550→605→544.5→490.05  (% returns: 0.1, 0.1, -0.1, -0.1)
// Cross product sum = 0 → ρ = 0.
// Equal weights → HHI = 5000, CWHHI = 5000
function fixtureZeroCorr(): { tx: string; prices: string; asOf: string } {
  return {
    tx: `
      INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, exchange)
      VALUES
        ('2026-01-01', 'USD',  'DEPOSIT', 1000, NULL, 0, 'USD', 'bank'),
        ('2026-01-01', 'ONEX', 'BUY',     4,    100,  0, 'USD', 'IBKR'),
        ('2026-01-01', 'TWOX', 'BUY',     0.8,  500,  0, 'USD', 'IBKR')
    `,
    prices: `
      INSERT INTO prices (ticker, date, price)
      VALUES
        ('ONEX', '2026-01-01', 100.0),
        ('ONEX', '2026-01-02', 110.0),
        ('ONEX', '2026-01-03', 99.0),
        ('ONEX', '2026-01-04', 108.9),
        ('ONEX', '2026-01-05', 98.01),
        ('TWOX', '2026-01-01', 500.0),
        ('TWOX', '2026-01-02', 550.0),
        ('TWOX', '2026-01-03', 605.0),
        ('TWOX', '2026-01-04', 544.5),
        ('TWOX', '2026-01-05', 490.05)
    `,
    asOf: "2026-01-05",
  };
}

// ── Fixture D: single holding (degenerate) ──
function fixtureSingle(): { tx: string; prices: string; asOf: string } {
  return {
    tx: `
      INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, exchange)
      VALUES
        ('2026-01-01', 'USD',  'DEPOSIT', 1000, NULL, 0, 'USD', 'bank'),
        ('2026-01-01', 'SOLO', 'BUY',     5,    100,  0, 'USD', 'IBKR')
    `,
    prices: `
      INSERT INTO prices (ticker, date, price)
      VALUES
        ('SOLO', '2026-01-01', 100.0),
        ('SOLO', '2026-01-02', 110.0),
        ('SOLO', '2026-01-03', 121.0),
        ('SOLO', '2026-01-04', 133.1)
    `,
    asOf: "2026-01-04",
  };
}

// ── Fixture E: three assets, two with prices + one cash only ──
// AAPL, GOOGL have prices; CASH has none.
// Should handle cash exclusion from correlation gracefully.
function fixtureCashExcluded(): { tx: string; prices: string; asOf: string } {
  return {
    tx: `
      INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, exchange)
      VALUES
        ('2026-01-01', 'USD',   'DEPOSIT', 2000, NULL, 0, 'USD', 'bank'),
        ('2026-01-01', 'AAPL',  'BUY',     10,   50,   0, 'USD', 'IBKR'),
        ('2026-01-01', 'GOOGL', 'BUY',     5,    100,  0, 'USD', 'IBKR')
    `,
    prices: `
      INSERT INTO prices (ticker, date, price)
      VALUES
        ('AAPL',  '2026-01-01', 50.0),
        ('AAPL',  '2026-01-02', 55.0),
        ('AAPL',  '2026-01-03', 60.5),
        ('AAPL',  '2026-01-04', 66.55),
        ('GOOGL', '2026-01-01', 100.0),
        ('GOOGL', '2026-01-02', 110.0),
        ('GOOGL', '2026-01-03', 121.0),
        ('GOOGL', '2026-01-04', 133.1)
    `,
    asOf: "2026-01-04",
  };
}

// ── Fixture F: p_min_correlation filter ──
// Same as Fixture A (ρ=1.0) but filter at 0.9: pair passes.
// Then filter at 1.1: no pairs pass → avg/max/min = NULL.
function fixtureMinCorr(): { tx: string; prices: string; asOf: string } {
  return fixturePerfectCorr();
}

MAYBE_SKIP("integration: diversification_depth_sql", () => {
  const ddl = tempTableDDL();

  test("two perfectly-correlated assets: ρ=1, HHI=5000, eff=2, CWHHI=10000", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(ddl.transactions);
        await tx.unsafe(ddl.prices);

        const f = fixturePerfectCorr();
        await tx.unsafe(f.tx);
        await tx.unsafe(f.prices);

        const [row] = await tx.unsafe(
          `SELECT * FROM portfolio_diversification_depth_sql($1)`,
          [f.asOf],
        ) as any[];

        expect(row.as_of_date).toBe(f.asOf);

        // HHI: 0.5² + 0.5² = 0.5 → ×10000 = 5000
        expect(Number(row.hhi)).toBeCloseTo(5000, 1);
        expect(Number(row.effective_holdings)).toBeCloseTo(2.0, 3);

        // ρ = 1.0 for the single pair
        expect(Number(row.avg_pairwise_correlation)).toBeCloseTo(1.0, 4);
        expect(Number(row.max_pairwise_correlation)).toBeCloseTo(1.0, 4);
        expect(Number(row.min_pairwise_correlation)).toBeCloseTo(1.0, 4);

        // CWHHI = (0.25 + 0.25 + 2×0.5×0.5×1.0) × 10000 = 10000
        expect(Number(row.correlation_weighted_hhi)).toBeCloseTo(10000, 1);

        expect(Number(row.total_holdings)).toBeGreaterThanOrEqual(2);
      });
    } finally {
      await sql.end();
    }
  });

  test("perfectly negative correlation: ρ=-1, CWHHI=0", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(ddl.transactions);
        await tx.unsafe(ddl.prices);

        const f = fixtureNegCorr();
        await tx.unsafe(f.tx);
        await tx.unsafe(f.prices);

        const [row] = await tx.unsafe(
          `SELECT * FROM portfolio_diversification_depth_sql($1)`,
          [f.asOf],
        ) as any[];

        expect(Number(row.hhi)).toBeCloseTo(5000, 1);
        expect(Number(row.avg_pairwise_correlation)).toBeCloseTo(-1.0, 4);
        expect(Number(row.min_pairwise_correlation)).toBeCloseTo(-1.0, 4);

        // CWHHI with ρ=-1: perfectly diversifying → weighted HHI = 0
        expect(Number(row.correlation_weighted_hhi)).toBeCloseTo(0, 1);
      });
    } finally {
      await sql.end();
    }
  });

  test("uncorrelated pair: ρ≈0, CWHHI≈HHI", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(ddl.transactions);
        await tx.unsafe(ddl.prices);

        const f = fixtureZeroCorr();
        await tx.unsafe(f.tx);
        await tx.unsafe(f.prices);

        const [row] = await tx.unsafe(
          `SELECT * FROM portfolio_diversification_depth_sql($1)`,
          [f.asOf],
        ) as any[];

        expect(Number(row.avg_pairwise_correlation)).toBeCloseTo(0, 3);

        // With ρ≈0: CWHHI ≈ HHI (no correlation penalty or benefit)
        expect(Number(row.correlation_weighted_hhi)).toBeCloseTo(
          Number(row.hhi),
          1,
        );
      });
    } finally {
      await sql.end();
    }
  });

  test("single holding: NULL correlations, CWHHI=HHI=10000", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(ddl.transactions);
        await tx.unsafe(ddl.prices);

        const f = fixtureSingle();
        await tx.unsafe(f.tx);
        await tx.unsafe(f.prices);

        const [row] = await tx.unsafe(
          `SELECT * FROM portfolio_diversification_depth_sql($1)`,
          [f.asOf],
        ) as any[];

        // Single holding + cash: one priced asset → <2 → correlations NULL
        expect(row.avg_pairwise_correlation).toBeNull();
        expect(row.max_pairwise_correlation).toBeNull();
        expect(row.min_pairwise_correlation).toBeNull();

        // CWHHI should reduce to HHI when no pairs available
        expect(Number(row.correlation_weighted_hhi)).toBeCloseTo(
          Number(row.hhi),
          1,
        );
      });
    } finally {
      await sql.end();
    }
  });

  test("cash excluded from correlation but included in HHI", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(ddl.transactions);
        await tx.unsafe(ddl.prices);

        const f = fixtureCashExcluded();
        await tx.unsafe(f.tx);
        await tx.unsafe(f.prices);

        const [row] = await tx.unsafe(
          `SELECT * FROM portfolio_diversification_depth_sql($1)`,
          [f.asOf],
        ) as any[];

        // Two priced assets → should have non-NULL correlations
        expect(row.avg_pairwise_correlation).not.toBeNull();

        // total_holdings includes cash (3 allocations: AAPL, GOOGL, USD)
        expect(Number(row.total_holdings)).toBeGreaterThanOrEqual(2);

        // HHI < 10000 because cash dilutes concentration
        expect(Number(row.hhi)).toBeLessThan(10000);
      });
    } finally {
      await sql.end();
    }
  });

  test("p_min_correlation filter excludes weak pairs", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(ddl.transactions);
        await tx.unsafe(ddl.prices);

        const f = fixtureMinCorr();
        await tx.unsafe(f.tx);
        await tx.unsafe(f.prices);

        // With p_min_correlation=0.9: ρ=1.0 pair passes
        const [row1] = await tx.unsafe(
          `SELECT * FROM portfolio_diversification_depth_sql($1, $2, $3)`,
          [f.asOf, 252, 0.9],
        ) as any[];

        expect(row1.avg_pairwise_correlation).not.toBeNull();
        expect(Number(row1.avg_pairwise_correlation)).toBeCloseTo(1.0, 4);

        // With p_min_correlation=1.5: no pair passes → correlations NULL
        const [row2] = await tx.unsafe(
          `SELECT * FROM portfolio_diversification_depth_sql($1, $2, $3)`,
          [f.asOf, 252, 1.5],
        ) as any[];

        expect(row2.avg_pairwise_correlation).toBeNull();
        expect(row2.max_pairwise_correlation).toBeNull();
        expect(row2.min_pairwise_correlation).toBeNull();

        // CWHHI still computed using all pairs (not filtered), so it stays
        expect(Number(row2.correlation_weighted_hhi)).toBeCloseTo(10000, 1);
      });
    } finally {
      await sql.end();
    }
  });

  test("lookback_days restricts the window", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(ddl.transactions);
        await tx.unsafe(ddl.prices);

        const f = fixturePerfectCorr();
        await tx.unsafe(f.tx);
        await tx.unsafe(f.prices);

        // Window=1 day: only 1 price point per asset → not enough for returns (<2) → no pairs
        const [row] = await tx.unsafe(
          `SELECT * FROM portfolio_diversification_depth_sql($1, $2, $3)`,
          [f.asOf, 1, 0.0],
        ) as any[];

        // Not enough priced assets (<2 returns needed) → correlations NULL
        expect(row.avg_pairwise_correlation).toBeNull();
      });
    } finally {
      await sql.end();
    }
  });
});
