import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

MAYBE_SKIP("integration: income command", () => {
  test(
    "portfolio_income_sql returns correct per-asset aggregates with FX conversion",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          // AAPL pays USD dividends, SAP.DE pays EUR dividends
          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-01-15', 'USD', 'DEPOSIT', 10000, NULL, 0, 'USD', NULL),
              ('2026-01-20', 'AAPL', 'DIVIDEND', 0.25, NULL, 0, 'USD', NULL),
              ('2026-02-20', 'AAPL', 'DIVIDEND', 0.25, NULL, 0, 'USD', NULL),
              ('2026-03-20', 'AAPL', 'DIVIDEND', 0.30, NULL, 0, 'USD', NULL),
              ('2026-01-31', 'SAP.DE', 'DIVIDEND', 0.50, NULL, 0, 'EUR', NULL),
              ('2026-02-28', 'SAP.DE', 'DIVIDEND', 0.50, NULL, 0, 'EUR', NULL),
              ('2026-03-15', 'USD', 'INTEREST', 5.00, NULL, 0, 'USD', NULL)
          `);

          // Prices for FX conversion of EUR dividends at their dates
          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('EURUSD=X', '2026-01-31', 1.10),
              ('EURUSD=X', '2026-02-28', 1.08),
              ('EURUSD=X', '2026-03-15', 1.12)
          `);

          const asOf = "2026-03-31";

          // AAPL dividends: 0.25 + 0.25 + 0.30 = 0.80 total, USD so 1:1 = 0.80
          // SAP.DE dividends: 0.50*1.10 + 0.50*1.08 = 0.55 + 0.54 = 1.09
          // INTEREST: 5.00 USD = 5.00
          // Total income: 0.80 + 1.09 + 5.00 = 6.89

          const rows = await tx.unsafe(
            `SELECT * FROM portfolio_income_sql($1)`,
            [asOf],
          ) as any[];

          const aapl = rows.find((r: any) => r.asset === "AAPL");
          const sap = rows.find((r: any) => r.asset === "SAP.DE");
          const interest = rows.find((r: any) => r.asset === "USD" && r.action === "INTEREST");

          expect(aapl).toBeDefined();
          expect(aapl.action).toBe("DIVIDEND");
          expect(Number(aapl.total_quantity)).toBeCloseTo(0.80, 6);
          expect(Number(aapl.usd_value)).toBeCloseTo(0.80, 2);
          expect(aapl.currency).toBe("USD");
          expect(Number(aapl.transaction_count)).toBe(3);

          expect(sap).toBeDefined();
          expect(sap.action).toBe("DIVIDEND");
          expect(Number(sap.total_quantity)).toBeCloseTo(1.00, 6);
          expect(Number(sap.usd_value)).toBeCloseTo(1.09, 2);
          expect(sap.currency).toBe("EUR");
          expect(Number(sap.transaction_count)).toBe(2);

          expect(interest).toBeDefined();
          expect(interest.action).toBe("INTEREST");
          expect(Number(interest.total_quantity)).toBeCloseTo(5.00, 6);
          expect(Number(interest.usd_value)).toBeCloseTo(5.00, 2);
          expect(interest.currency).toBe("USD");
          expect(Number(interest.transaction_count)).toBe(1);

          // Verify status income field matches sum of income rows
          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [asOf],
          ) as any[];

          const totalIncome = rows.reduce(
            (sum: number, r: any) => sum + Number(r.usd_value),
            0,
          );
          expect(Math.abs(Number(status.income) - totalIncome)).toBeLessThan(0.01);

          // Test from_date filter
          const fromFeb = await tx.unsafe(
            `SELECT * FROM portfolio_income_sql($1, $2)`,
            [asOf, "2026-02-01"],
          ) as any[];

          const fromFebTotal = fromFeb.reduce(
            (sum: number, r: any) => sum + Number(r.usd_value),
            0,
          );
          // Only Feb 20 AAPL (0.25), Feb 28 SAP (0.54), Mar 15 INTEREST (5.00) = 5.79
          // Actually AAPL Feb 20 = 0.25, SAP Feb 28 = 0.54, INTEREST Mar 15 = 5.00
          expect(fromFebTotal).toBeCloseTo(5.79, 2);

          // Test asset filter
          const aaplOnly = await tx.unsafe(
            `SELECT * FROM portfolio_income_sql($1, NULL, $2)`,
            [asOf, "AAPL"],
          ) as any[];

          expect(aaplOnly.length).toBe(1);
          expect(aaplOnly[0].asset).toBe("AAPL");
          expect(Number(aaplOnly[0].usd_value)).toBeCloseTo(0.80, 2);

          // Test empty result (future from_date)
          const empty = await tx.unsafe(
            `SELECT * FROM portfolio_income_sql($1, $2)`,
            [asOf, "2099-01-01"],
          ) as any[];
          expect(empty.length).toBe(0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );
});
