import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

MAYBE_SKIP("missing-price regression — recalc fails loud (#87)", () => {
  test("verify_held_prices_sql raises when a held non-cash asset has no price", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(`
          CREATE TEMP TABLE transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date DATE NOT NULL,
            asset VARCHAR NOT NULL,
            action VARCHAR NOT NULL,
            quantity DOUBLE PRECISION NOT NULL,
            asset_type VARCHAR,
            price DOUBLE PRECISION,
            currency VARCHAR,
            fees DOUBLE PRECISION,
            fee_currency VARCHAR,
            exchange VARCHAR,
            data_source VARCHAR,
            account VARCHAR,
            exchange_group_id TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP
          ) ON COMMIT DROP
        `);

        await tx.unsafe(`
          CREATE TEMP TABLE prices (
            date DATE NOT NULL,
            ticker VARCHAR NOT NULL,
            price DOUBLE PRECISION NOT NULL,
            PRIMARY KEY (date, ticker)
          ) ON COMMIT DROP
        `);

        await tx.unsafe(`
          INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
          VALUES ('2026-01-15', 'AAPL', 'BUY', 10, 150, 0, 'USD', NULL)
        `);

        // Deliberately do NOT insert AAPL price — price is missing
        // This MUST raise an exception, not silently write 0

        let caught = false;
        try {
          await tx.unsafe(`SELECT verify_held_prices_sql('2026-01-15'::DATE)`);
        } catch (e: any) {
          caught = true;
          expect(e.message).toContain("Price unavailable");
          expect(e.message).toContain("AAPL");
        }

        expect(caught).toBe(true);
      });
    } finally {
      await sql.end();
    }
  });

  test("verify_held_prices_sql raises when FX price is missing for foreign-currency stock", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(`
          CREATE TEMP TABLE transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date DATE NOT NULL,
            asset VARCHAR NOT NULL,
            action VARCHAR NOT NULL,
            quantity DOUBLE PRECISION NOT NULL,
            asset_type VARCHAR,
            price DOUBLE PRECISION,
            currency VARCHAR,
            fees DOUBLE PRECISION,
            fee_currency VARCHAR,
            exchange VARCHAR,
            data_source VARCHAR,
            account VARCHAR,
            exchange_group_id TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP
          ) ON COMMIT DROP
        `);

        await tx.unsafe(`
          CREATE TEMP TABLE prices (
            date DATE NOT NULL,
            ticker VARCHAR NOT NULL,
            price DOUBLE PRECISION NOT NULL,
            PRIMARY KEY (date, ticker)
          ) ON COMMIT DROP
        `);

        await tx.unsafe(`
          INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
          VALUES ('2026-01-15', 'SAP.DE', 'BUY', 5, 120, 0, 'EUR', NULL)
        `);

        // Insert stock price but NOT EURUSD=X FX rate
        await tx.unsafe(`
          INSERT INTO prices (ticker, date, price)
          VALUES ('SAP.DE', '2026-01-15', 120)
        `);

        let caught = false;
        try {
          await tx.unsafe(`SELECT verify_held_prices_sql('2026-01-15'::DATE)`);
        } catch (e: any) {
          caught = true;
          expect(e.message).toContain("FX price unavailable");
          expect(e.message).toContain("EURUSD=X");
        }

        expect(caught).toBe(true);
      });
    } finally {
      await sql.end();
    }
  });

  test("verify_held_prices_sql succeeds when all prices are present", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(`
          CREATE TEMP TABLE transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date DATE NOT NULL,
            asset VARCHAR NOT NULL,
            action VARCHAR NOT NULL,
            quantity DOUBLE PRECISION NOT NULL,
            asset_type VARCHAR,
            price DOUBLE PRECISION,
            currency VARCHAR,
            fees DOUBLE PRECISION,
            fee_currency VARCHAR,
            exchange VARCHAR,
            data_source VARCHAR,
            account VARCHAR,
            exchange_group_id TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP
          ) ON COMMIT DROP
        `);

        await tx.unsafe(`
          CREATE TEMP TABLE prices (
            date DATE NOT NULL,
            ticker VARCHAR NOT NULL,
            price DOUBLE PRECISION NOT NULL,
            PRIMARY KEY (date, ticker)
          ) ON COMMIT DROP
        `);

        await tx.unsafe(`
          INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
          VALUES
            ('2026-01-15', 'AAPL',   'BUY', 10, 150, 0, 'USD', NULL),
            ('2026-01-15', 'SAP.DE', 'BUY',  5, 120, 0, 'EUR', NULL)
        `);

        await tx.unsafe(`
          INSERT INTO prices (ticker, date, price)
          VALUES
            ('AAPL',     '2026-01-15', 150),
            ('SAP.DE',   '2026-01-15', 120),
            ('EURUSD=X', '2026-01-15', 1.10)
        `);

        await tx.unsafe(`SELECT verify_held_prices_sql('2026-01-15'::DATE)`);
        expect(true).toBe(true);
      });
    } finally {
      await sql.end();
    }
  });

  test("refresh_daily_returns_sql raises when held asset has no price", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      await sql.begin(async (tx: any) => {
        await tx.unsafe(`
          CREATE TEMP TABLE transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date DATE NOT NULL,
            asset VARCHAR NOT NULL,
            action VARCHAR NOT NULL,
            quantity DOUBLE PRECISION NOT NULL,
            asset_type VARCHAR,
            price DOUBLE PRECISION,
            currency VARCHAR,
            fees DOUBLE PRECISION,
            fee_currency VARCHAR,
            exchange VARCHAR,
            data_source VARCHAR,
            account VARCHAR,
            exchange_group_id TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP
          ) ON COMMIT DROP
        `);

        await tx.unsafe(`
          CREATE TEMP TABLE prices (
            date DATE NOT NULL,
            ticker VARCHAR NOT NULL,
            price DOUBLE PRECISION NOT NULL,
            PRIMARY KEY (date, ticker)
          ) ON COMMIT DROP
        `);

        await tx.unsafe(`
          CREATE TEMP TABLE daily_returns (
            date DATE PRIMARY KEY,
            portfolio_value DOUBLE PRECISION NOT NULL,
            portfolio_daily_return DOUBLE PRECISION,
            investment_return DOUBLE PRECISION,
            cash_flow_impact DOUBLE PRECISION,
            adjusted_base DOUBLE PRECISION
          ) ON COMMIT DROP
        `);

        await tx.unsafe(`
          CREATE TEMP TABLE service_state (
            state_key VARCHAR PRIMARY KEY,
            state_value VARCHAR,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          ) ON COMMIT DROP
        `);

        // Buy AAPL but no price in prices table
        await tx.unsafe(`
          INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
          VALUES ('2026-01-15', 'AAPL', 'BUY', 10, 150, 0, 'USD', NULL)
        `);

        let caught = false;
        try {
          await tx.unsafe(`SELECT refresh_daily_returns_sql()`);
        } catch (e: any) {
          caught = true;
          expect(e.message).toContain("Price unavailable");
          expect(e.message).toContain("AAPL");
        }

        expect(caught).toBe(true);
      });
    } finally {
      await sql.end();
    }
  });

  test("COALESCE-to-0 guard: recalc raises on missing price, no portfolio_value rows written", async () => {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      let raised = false;
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE daily_returns (
              date DATE PRIMARY KEY,
              portfolio_value DOUBLE PRECISION NOT NULL,
              portfolio_daily_return DOUBLE PRECISION,
              investment_return DOUBLE PRECISION,
              cash_flow_impact DOUBLE PRECISION,
              adjusted_base DOUBLE PRECISION
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE service_state (
              state_key VARCHAR PRIMARY KEY,
              state_value VARCHAR,
              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES ('2026-01-15', 'MSFT', 'BUY', 20, 400, 0, 'USD', NULL)
          `);

          // No MSFT price — must raise, not silently write 0
          await tx.unsafe(`SELECT refresh_daily_returns_sql()`);
        });
      } catch (e: any) {
        raised = true;
        expect(e.message).toContain("Price unavailable");
        expect(e.message).toContain("MSFT");
      }

      expect(raised).toBe(true);
    } finally {
      await sql.end();
    }
  });
});
