import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

function tempTableDDL() {
  return {
    transactions: `
      CREATE TEMP TABLE transactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date DATE NOT NULL,
        asset VARCHAR NOT NULL,
        action VARCHAR NOT NULL,
        quantity DOUBLE PRECISION NOT NULL,
        asset_type VARCHAR,
        price DOUBLE PRECISION,
        currency VARCHAR,
        fees DOUBLE PRECISION,
        fee_currency VARCHAR,
        exchange VARCHAR,
        data_source VARCHAR,
        account VARCHAR,
        exchange_group_id TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
      ) ON COMMIT DROP
    `,
    prices: `
      CREATE TEMP TABLE prices (
        date DATE NOT NULL,
        ticker VARCHAR NOT NULL,
        price DOUBLE PRECISION NOT NULL,
        PRIMARY KEY (date, ticker)
      ) ON COMMIT DROP
    `,
    daily_returns: `
      CREATE TEMP TABLE daily_returns (
        date DATE PRIMARY KEY,
        portfolio_value DOUBLE PRECISION NOT NULL,
        portfolio_daily_return DOUBLE PRECISION,
        investment_return DOUBLE PRECISION,
        cash_flow_impact DOUBLE PRECISION,
        adjusted_base DOUBLE PRECISION
      ) ON COMMIT DROP
    `,
  };
}

// Fixture A: no cash flows after day 0.
// deposit $1000 + buy 10×TESTX@100 on day 0; TESTX price 100→110→121→121→121
function fixtureNoFlows(): { tx: string; prices: string } {
  return {
    tx: `
      INSERT INTO transactions (date, asset, action, quantity, price, fees, currency)
      VALUES
        ('2026-01-01', 'USD',   'DEPOSIT', 1000, NULL, 0, 'USD'),
        ('2026-01-01', 'TESTX', 'BUY',     10,   100,  0, 'USD')
    `,
    prices: `
      INSERT INTO prices (ticker, date, price)
      VALUES
        ('TESTX', '2026-01-01', 100),
        ('TESTX', '2026-01-02', 110),
        ('TESTX', '2026-01-03', 121),
        ('TESTX', '2026-01-04', 121),
        ('TESTX', '2026-01-05', 121)
    `,
  };
}

// Fixture B: mid-series deposit on day 3 so cash flows exist.
function fixtureWithFlows(): { tx: string; prices: string } {
  return {
    tx: `
      INSERT INTO transactions (date, asset, action, quantity, price, fees, currency)
      VALUES
        ('2026-01-01', 'USD',   'DEPOSIT', 1000, NULL, 0, 'USD'),
        ('2026-01-01', 'TESTX', 'BUY',     10,   100,  0, 'USD'),
        ('2026-01-03', 'USD',   'DEPOSIT', 500,  NULL, 0, 'USD')
    `,
    prices: `
      INSERT INTO prices (ticker, date, price)
      VALUES
        ('TESTX', '2026-01-01', 100),
        ('TESTX', '2026-01-02', 110),
        ('TESTX', '2026-01-03', 121),
        ('TESTX', '2026-01-04', 121),
        ('TESTX', '2026-01-05', 121)
    `,
  };
}

MAYBE_SKIP("integration: perf correctness (#232 + #225)", () => {
  test(
    "#232 unit-of-truth: investment_return == 10 (NOT 11) on 110→121 day, equals portfolio_daily_return",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          const ddl = tempTableDDL();
          await tx.unsafe(ddl.transactions);
          await tx.unsafe(ddl.prices);
          await tx.unsafe(ddl.daily_returns);

          const f = fixtureNoFlows();
          await tx.unsafe(f.tx);
          await tx.unsafe(f.prices);

          await tx.unsafe(`SELECT refresh_daily_returns_sql()`);

          const rows = await tx.unsafe(
            `SELECT date, portfolio_daily_return, investment_return
             FROM daily_returns
             ORDER BY date`
          ) as any[];

          // Day index: 0=2026-01-01, 1=01-02, 2=01-03, 3=01-04, 4=01-05
          const day2 = rows[2]; // 2026-01-03: price 110→121

          expect(Number(day2.portfolio_daily_return)).toBeCloseTo(10.0, 4);
          expect(Number(day2.investment_return)).toBeCloseTo(10.0, 4);
          // The BUG would have produced investment_return == 11.0 here
          expect(Number(day2.investment_return)).not.toBeCloseTo(11.0, 0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "#232 metric: time_weighted_return_pct ≈ 21.0, total_gain ≈ 210",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          const ddl = tempTableDDL();
          await tx.unsafe(ddl.transactions);
          await tx.unsafe(ddl.prices);
          await tx.unsafe(ddl.daily_returns);

          const f = fixtureNoFlows();
          await tx.unsafe(f.tx);
          await tx.unsafe(f.prices);

          await tx.unsafe(`SELECT refresh_daily_returns_sql()`);

          const [perf] = await tx.unsafe(
            `SELECT * FROM portfolio_performance_sql('2026-01-05'::DATE)`
          ) as any[];

          expect(Number(perf.time_weighted_return_pct)).toBeCloseTo(21.0, 2);
          // Before fix: was 22.1 with the bug
          expect(Number(perf.time_weighted_return_pct)).not.toBeCloseTo(22.1, 0);
          expect(Number(perf.total_gain)).toBeCloseTo(210, 2);
          // Before fix: was 221 with the bug
          expect(Number(perf.total_gain)).not.toBeCloseTo(221, 0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "#225 distinctness: with mid-series deposit, total_return_pct ≠ time_weighted_return_pct",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          const ddl = tempTableDDL();
          await tx.unsafe(ddl.transactions);
          await tx.unsafe(ddl.prices);
          await tx.unsafe(ddl.daily_returns);

          const f = fixtureWithFlows();
          await tx.unsafe(f.tx);
          await tx.unsafe(f.prices);

          await tx.unsafe(`SELECT refresh_daily_returns_sql()`);

          const [perf] = await tx.unsafe(
            `SELECT * FROM portfolio_performance_sql('2026-01-05'::DATE)`
          ) as any[];

          const twr = Number(perf.time_weighted_return_pct);
          const tot = Number(perf.total_return_pct);

          // TWR is cash-flow-neutral: should still be 21.0
          expect(twr).toBeCloseTo(21.0, 2);

          // total_return_pct includes cash flow effect:
          // end_value = 1710 (stock 1210 + cash 500), start_value = 1000
          // (1710 - 1000) / 1000 * 100 = 71.0
          expect(tot).toBeCloseTo(71.0, 2);

          // They must differ (before fix they were aliases)
          expect(tot).not.toBeCloseTo(twr, 4);
          const diff = Math.abs(tot - twr);
          expect(diff).toBeGreaterThan(1.0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "#225 value: total_return_pct == ((end_value - start_value)/start_value)*100 for no-flow fixture",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          const ddl = tempTableDDL();
          await tx.unsafe(ddl.transactions);
          await tx.unsafe(ddl.prices);
          await tx.unsafe(ddl.daily_returns);

          const f = fixtureNoFlows();
          await tx.unsafe(f.tx);
          await tx.unsafe(f.prices);

          await tx.unsafe(`SELECT refresh_daily_returns_sql()`);

          const [perf] = await tx.unsafe(
            `SELECT * FROM portfolio_performance_sql('2026-01-05'::DATE)`
          ) as any[];

          const sv = Number(perf.start_value);
          const ev = Number(perf.end_value);
          const tot = Number(perf.total_return_pct);

          // Hand-check: end_value=1210, start_value=1000
          expect(sv).toBeCloseTo(1000, 2);
          expect(ev).toBeCloseTo(1210, 2);

          const expected = ((ev - sv) / sv) * 100;
          expect(tot).toBeCloseTo(expected, 4);
          // Because there are no flows, this also equals TWR
          expect(tot).toBeCloseTo(21.0, 2);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );
});
