import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

MAYBE_SKIP("integration: realized-gains command (#214)", () => {
  test(
    "multi-BUY, multi-SELL FIFO: oldest lot first, correct holding_days, per-lot detail",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-01-01', 'USD', 'DEPOSIT', 10000, NULL, 0, 'USD', NULL),
              ('2026-01-02', 'AAPL', 'BUY', 10, 150, 0, 'USD', NULL),
              ('2026-01-05', 'AAPL', 'BUY', 10, 110, 0, 'USD', NULL),
              ('2026-01-10', 'AAPL', 'SELL', 15, 120, 0, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-01-01', 150),
              ('AAPL', '2026-01-02', 150),
              ('AAPL', '2026-01-05', 110),
              ('AAPL', '2026-01-10', 120)
          `);

          const asOf = "2026-01-10";

          const detailRows = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, $1, NULL) ORDER BY sell_date, matched_buy_date`,
            [asOf],
          ) as any[];

          // Hand-calculated FIFO:
          // SELL 15 @ $120, proceeds = 15 * 120 = 1800
          // Lot1 (oldest): 10 AAPL @ $150 → consume 10
          //   cost_consumed = 10 * 150 = 1500
          //   proceeds_share = 1800 * (10 / 15) = 1200
          //   realized = 1200 - 1500 = -300
          //   holding_days = 8 (Jan 2 → Jan 10)
          //
          // Lot2: 10 AAPL @ $110 → consume 5
          //   cost_consumed = 5 * 110 = 550
          //   proceeds_share = 1800 * (5 / 15) = 600
          //   realized = 600 - 550 = +50
          //   holding_days = 5 (Jan 5 → Jan 10)
          //
          // Total realized = -250

          expect(detailRows.length).toBe(2);

          const [row1, row2] = detailRows;
          expect(row1.asset).toBe("AAPL");
          expect(Number(row1.sell_quantity)).toBeCloseTo(10, 6);
          expect(Number(row1.proceeds_usd)).toBeCloseTo(1200, 2);
          expect(Number(row1.cost_basis_usd)).toBeCloseTo(1500, 2);
          expect(Number(row1.realized_gain)).toBeCloseTo(-300, 2);
          expect(Number(row1.holding_days)).toBe(8);

          expect(Number(row2.sell_quantity)).toBeCloseTo(5, 6);
          expect(Number(row2.proceeds_usd)).toBeCloseTo(600, 2);
          expect(Number(row2.cost_basis_usd)).toBeCloseTo(550, 2);
          expect(Number(row2.realized_gain)).toBeCloseTo(50, 2);
          expect(Number(row2.holding_days)).toBe(5);

          // FIFO: oldest first → row1 buy_id < row2 buy_id
          expect(Number(row1.matched_buy_id)).toBeLessThan(Number(row2.matched_buy_id));
          expect(row1.matched_buy_date).toBe("2026-01-02");
          expect(row2.matched_buy_date).toBe("2026-01-05");
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "consistency invariant: SUM(detail realized_gain) == status.realized_gain (multi-BUY/SELL)",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-01-01', 'USD', 'DEPOSIT', 20000, NULL, 0, 'USD', NULL),
              ('2026-01-02', 'AAPL', 'BUY', 20, 100, 5, 'USD', NULL),
              ('2026-01-03', 'MSFT', 'BUY', 10, 200, 3, 'USD', NULL),
              ('2026-01-10', 'AAPL', 'SELL', 8, 110, 2, 'USD', NULL),
              ('2026-01-15', 'MSFT', 'SELL', 5, 210, 1, 'USD', NULL),
              ('2026-01-20', 'AAPL', 'SELL', 6, 115, 1, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-01-02', 100),
              ('AAPL', '2026-01-10', 110),
              ('AAPL', '2026-01-20', 115),
              ('MSFT', '2026-01-03', 200),
              ('MSFT', '2026-01-15', 210)
          `);

          const asOf = "2026-01-20";

          const detailRows = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, $1, NULL)`,
            [asOf],
          ) as any[];

          const detailTotal = detailRows.reduce(
            (sum: number, r: any) => sum + Number(r.realized_gain),
            0,
          );

          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [asOf],
          ) as any[];

          const statusRealized = Number(status.realized_gain);

          // Hand-calculated FIFO validation:
          // AAPL:
          //   BUY 20 @ 100 + 5 fee = 2005, unit_cost = 100.25
          //   SELL 8 @ 110 - 2 fee → proceeds = 878
          //     consume 8: cost = 8*100.25=802, proceeds_share=878, realized=76
          //     remaining: 12 @ 100.25
          //   SELL 6 @ 115 - 1 fee → proceeds = 689
          //     consume 6: cost = 6*100.25=601.50, proceeds_share=689, realized=87.50
          //     remaining: 6 @ 100.25
          //   AAPL realized = 76 + 87.50 = 163.50
          //
          // MSFT:
          //   BUY 10 @ 200 + 3 fee = 2003, unit_cost = 200.30
          //   SELL 5 @ 210 - 1 fee → proceeds = 1049
          //     consume 5: cost = 5*200.30=1001.50, proceeds_share=1049, realized=47.50
          //   MSFT realized = 47.50
          //
          // Total realized = 163.50 + 47.50 = 211.00

          expect(detailTotal).toBeCloseTo(211.00, 2);
          expect(statusRealized).toBeCloseTo(211.00, 2);
          expect(statusRealized).toBeCloseTo(detailTotal, 2);
          expect(Math.abs(statusRealized - detailTotal)).toBeLessThan(0.02);

          // Middle date: as-of 2026-01-03 (before any SELL) → realized=0
          const detailEarly = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, '2026-01-03', NULL)`,
          ) as any[];
          expect(detailEarly.length).toBe(0);

          const [statusEarly] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql('2026-01-03')`,
          ) as any[];
          expect(Number(statusEarly.realized_gain)).toBe(0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "split fixture: BUY 100 @150, SPLIT 4, SELL 100 @50 → realized=1250, consistency invariant",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-06-01', 'USD', 'DEPOSIT', 15000, NULL, 0, 'USD', NULL),
              ('2026-06-02', 'AAPL', 'BUY', 100, 150, 0, 'USD', NULL),
              ('2026-06-03', 'AAPL', 'SPLIT', 4, NULL, NULL, NULL, NULL),
              ('2026-06-04', 'AAPL', 'SELL', 100, 50, 0, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-06-02', 150),
              ('AAPL', '2026-06-03', 37.50),
              ('AAPL', '2026-06-04', 50)
          `);

          const asOf = "2026-06-04";

          const detailRows = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, $1, NULL)`,
            [asOf],
          ) as any[];

          // Expected: 1 match row
          // BUY 100 @ 150 → cost 15000, unit_cost 150
          // SPLIT 4 → remaining 400 @ unit_cost 37.50 (150/4)
          // SELL 100 @ 50 → proceeds 5000, cost 100*37.50 = 3750, realized = 1250
          // holding_days = 2 (Jun 2 → Jun 4)

          expect(detailRows.length).toBe(1);
          expect(detailRows[0].asset).toBe("AAPL");
          expect(Number(detailRows[0].sell_quantity)).toBeCloseTo(100, 6);
          expect(Number(detailRows[0].proceeds_usd)).toBeCloseTo(5000, 2);
          expect(Number(detailRows[0].cost_basis_usd)).toBeCloseTo(3750, 2);
          expect(Number(detailRows[0].realized_gain)).toBeCloseTo(1250, 2);
          expect(Number(detailRows[0].holding_days)).toBe(2);

          // SPLIT should not produce any realized-gain rows (no taxable event)
          const splitOnly = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, '2026-06-03', NULL)`,
          ) as any[];
          expect(splitOnly.length).toBe(0);

          // Consistency invariant
          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [asOf],
          ) as any[];
          const detailTotal = detailRows.reduce(
            (sum: number, r: any) => sum + Number(r.realized_gain),
            0,
          );
          expect(detailTotal).toBeCloseTo(1250, 2);
          expect(Number(status.realized_gain)).toBeCloseTo(1250, 2);
          expect(Math.abs(Number(status.realized_gain) - detailTotal)).toBeLessThan(0.02);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "by-year aggregation: short-term vs long-term split at 365 days, tax_year grouping",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          // Two tax years: 2025 and 2026
          // 2025: BUY 2025-01-15, SELL 2025-12-15 = short-term (334 days)
          // 2026: BUY 2025-01-15, SELL 2026-03-15 = long-term (424 days); SELL 2026-06-15 short-term (30 days from 2026 BUY)
          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2025-01-01', 'USD', 'DEPOSIT', 20000, NULL, 0, 'USD', NULL),
              ('2025-01-15', 'AAPL', 'BUY', 20, 100, 0, 'USD', NULL),
              ('2025-12-15', 'AAPL', 'SELL', 10, 110, 0, 'USD', NULL),
              ('2026-01-15', 'AAPL', 'BUY', 5, 120, 0, 'USD', NULL),
              ('2026-03-15', 'AAPL', 'SELL', 10, 130, 0, 'USD', NULL),
              ('2026-06-15', 'AAPL', 'SELL', 5, 140, 0, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2025-01-15', 100),
              ('AAPL', '2025-12-15', 110),
              ('AAPL', '2026-01-15', 120),
              ('AAPL', '2026-03-15', 130),
              ('AAPL', '2026-06-15', 140)
          `);

          // Hand-calculated FIFO:
          // Lot1: 20 AAPL @ 100 (2025-01-15)
          // SELL 10 @ 110 (2025-12-15): consume 10, proceeds=1100, cost=1000, gain=100
          //   holding=334 days → short-term (≤365)
          //   remaining: 10 @ 100
          //
          // Lot2: 5 AAPL @ 120 (2026-01-15)
          // SELL 10 @ 130 (2026-03-15):
          //   consume lot1 remaining 10: proceeds=1300, cost=1000, gain=300
          //   holding=424 days (2025-01-15→2026-03-15) → long-term (>365)
          //   remaining: 0 from lot1, 5 from lot2
          //
          // SELL 5 @ 140 (2026-06-15):
          //   consume lot2: 5, proceeds=700, cost=600, gain=100
          //   holding=151 days (2026-01-15→2026-06-15) → short-term
          //
          // By year:
          // 2025: total=100, short=100, long=0, txn_count=1
          // 2026: total=400, short=100, long=300, txn_count=2

          const byYear = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_by_year_sql(NULL, 2026)`,
          ) as any[];

          expect(byYear.length).toBe(2);

          const yr2025 = byYear.find((r: any) => Number(r.tax_year) === 2025);
          const yr2026 = byYear.find((r: any) => Number(r.tax_year) === 2026);

          expect(yr2025).toBeDefined();
          expect(Number(yr2025.total_realized_gain)).toBeCloseTo(100, 2);
          expect(Number(yr2025.short_term_gain)).toBeCloseTo(100, 2);
          expect(Number(yr2025.long_term_gain)).toBeCloseTo(0, 2);
          expect(Number(yr2025.transaction_count)).toBe(1);

          expect(yr2026).toBeDefined();
          expect(Number(yr2026.total_realized_gain)).toBeCloseTo(400, 2);
          expect(Number(yr2026.short_term_gain)).toBeCloseTo(100, 2);
          expect(Number(yr2026.long_term_gain)).toBeCloseTo(300, 2);
          expect(Number(yr2026.transaction_count)).toBe(2);

          // By-year totals should match detail totals
          const detailAll = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, '2026-06-15', NULL)`,
          ) as any[];
          const detailTotal = detailAll.reduce(
            (sum: number, r: any) => sum + Number(r.realized_gain),
            0,
          );
          const byYearTotal = byYear.reduce(
            (sum: number, r: any) => sum + Number(r.total_realized_gain),
            0,
          );
          expect(detailTotal).toBeCloseTo(byYearTotal, 2);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "asset filter and date range filter work correctly",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-01-01', 'USD', 'DEPOSIT', 10000, NULL, 0, 'USD', NULL),
              ('2026-01-02', 'AAPL', 'BUY', 10, 100, 0, 'USD', NULL),
              ('2026-01-10', 'AAPL', 'SELL', 5, 110, 0, 'USD', NULL),
              ('2026-01-02', 'MSFT', 'BUY', 10, 200, 0, 'USD', NULL),
              ('2026-01-15', 'MSFT', 'SELL', 5, 210, 0, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-01-02', 100),
              ('AAPL', '2026-01-10', 110),
              ('MSFT', '2026-01-02', 200),
              ('MSFT', '2026-01-15', 210)
          `);

          // Filter by asset
          const aaplOnly = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, '2026-01-20', 'AAPL')`,
          ) as any[];
          expect(aaplOnly.length).toBe(1);
          expect(aaplOnly[0].asset).toBe("AAPL");

          // Filter by date range
          const fromJan10 = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql('2026-01-10', '2026-01-20', NULL)`,
          ) as any[];
          expect(fromJan10.length).toBe(2);

          // as_of filter excludes later SELLs
          const asOfJan10 = await tx.unsafe(
            `SELECT * FROM portfolio_realized_gains_sql(NULL, '2026-01-10', NULL)`,
          ) as any[];
          expect(asOfJan10.length).toBe(1);
          expect(asOfJan10[0].asset).toBe("AAPL");
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );
});
