import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

// Verifies the refresh-audit checkpoints folded into get_required_price_checkpoints_sql (#325).
// A same-day `price_refresh` row in refresh_log with rows_affected > 0 must force a
// CURRENT_DATE checkpoint for every non-cash required ticker, so a bucket-wide zero-row
// fetch can't hide until stale_tickers_sql() ages out. A zero-row refresh (closed market)
// must NOT add audit checkpoints.

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

MAYBE_SKIP("integration: refresh-audit checkpoints fold (#325)", () => {
  // refreshRows: rows_affected for a CURRENT_DATE price_refresh log row; null = no row.
  async function checkpointSet(refreshRows: number | null): Promise<{ today: string; set: Set<string> }> {
    const sql = new SQL(DB_URL!, { max: 1 });
    try {
      return await sql.begin(async (tx: any) => {
        await tx.unsafe(`
          CREATE TEMP TABLE transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date DATE NOT NULL, asset VARCHAR NOT NULL, action VARCHAR NOT NULL,
            quantity DOUBLE PRECISION NOT NULL, asset_type VARCHAR, price DOUBLE PRECISION,
            currency VARCHAR, fees DOUBLE PRECISION, fee_currency VARCHAR, exchange VARCHAR,
            data_source VARCHAR, account VARCHAR, exchange_group_id TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP
          ) ON COMMIT DROP
        `);
        await tx.unsafe(`
          CREATE TEMP TABLE prices (
            date DATE NOT NULL, ticker VARCHAR NOT NULL, price DOUBLE PRECISION NOT NULL,
            PRIMARY KEY (date, ticker)
          ) ON COMMIT DROP
        `);
        await tx.unsafe(`
          CREATE TEMP TABLE refresh_log (
            refresh_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            refresh_date DATE NOT NULL, refresh_type VARCHAR NOT NULL, rows_affected INTEGER
          ) ON COMMIT DROP
        `);

        // One non-cash required ticker (AAPL stock).
        await tx.unsafe(`
          INSERT INTO transactions (date, asset, action, quantity, price, fees, currency)
          VALUES ('2026-01-02', 'AAPL', 'BUY', 10, 150, 0, 'USD')
        `);

        if (refreshRows !== null) {
          await tx.unsafe(
            `INSERT INTO refresh_log (refresh_date, refresh_type, rows_affected)
             VALUES (CURRENT_DATE, 'price_refresh', $1)`,
            [refreshRows],
          );
        }

        const rows = (await tx.unsafe(
          `SELECT ticker, checkpoint_date::text AS d
           FROM get_required_price_checkpoints_sql(CURRENT_DATE)`,
        )) as Array<{ ticker: string; d: string }>;
        const [{ today }] = (await tx.unsafe(
          `SELECT CURRENT_DATE::text AS today`,
        )) as Array<{ today: string }>;

        return { today, set: new Set(rows.map((r) => `${r.ticker}|${r.d}`)) };
      });
    } finally {
      await sql.end();
    }
  }

  test("positive same-day refresh forces a CURRENT_DATE checkpoint, adds only today rows", async () => {
    const withAudit = await checkpointSet(5);
    const noRefresh = await checkpointSet(null);
    const today = withAudit.today;

    // Audit guarantees today's checkpoint regardless of weekday.
    expect(withAudit.set.has(`AAPL|${today}`)).toBe(true);

    // Nothing the base set produced is dropped.
    for (const x of noRefresh.set) expect(withAudit.set.has(x)).toBe(true);

    // Anything the audit adds is dated CURRENT_DATE — never a different date.
    for (const x of withAudit.set) {
      if (!noRefresh.set.has(x)) expect(x.endsWith(`|${today}`)).toBe(true);
    }
  });

  test("zero-row refresh (closed market) adds no audit checkpoints", async () => {
    const zero = await checkpointSet(0);
    const noRefresh = await checkpointSet(null);

    // rows_affected = 0 must behave exactly like no refresh row at all.
    expect([...zero.set].sort()).toEqual([...noRefresh.set].sort());
  });
});
