import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

MAYBE_SKIP("integration: SPLIT corporate action (#216)", () => {
  test(
    "forward split: BUY 100 AAPL @ $150, SPLIT 4:1 → net qty 400, cost_basis unchanged, unit_cost divided",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-06-01', 'USD', 'DEPOSIT', 15000, NULL, 0, 'USD', NULL),
              ('2026-06-02', 'AAPL', 'BUY', 100, 150, 0, 'USD', NULL),
              ('2026-06-03', 'AAPL', 'SPLIT', 4, NULL, NULL, NULL, NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-06-01', 150),
              ('AAPL', '2026-06-02', 150),
              ('AAPL', '2026-06-03', 37.50)
          `);

          const asOf = "2026-06-03";

          const [fifo] = await tx.unsafe(
            `SELECT * FROM portfolio_fifo_metrics_sql($1)`,
            [asOf],
          ) as any[];

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1)`,
            [asOf],
          ) as any[];

          const cash = await tx.unsafe(
            `SELECT * FROM portfolio_cash_sql($1)`,
            [asOf],
          ) as any[];

          const aaplRow = allocation.find((r: any) => r.asset === "AAPL");
          expect(aaplRow).toBeDefined();
          expect(aaplRow.net_quantity).toBe(400);

          const costBasis = Number(fifo.cost_basis);
          expect(costBasis).toBe(15000);

          const realizedGain = Number(fifo.realized_gain);
          expect(realizedGain).toBe(0);

          const marketValue = 400 * 37.50;
          const unrealizedGain = Number(fifo.unrealized_gain);
          expect(unrealizedGain).toBeCloseTo(marketValue - costBasis, 2);

          const cashTotal = cash.reduce(
            (sum: number, r: any) => sum + Number(r.usd_value),
            0,
          );
          expect(cashTotal).toBeCloseTo(15000 - 100 * 150, 2);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "SELL after split: FIFO computes realized gain off split-adjusted unit cost",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-06-01', 'USD', 'DEPOSIT', 15000, NULL, 0, 'USD', NULL),
              ('2026-06-02', 'AAPL', 'BUY', 100, 150, 0, 'USD', NULL),
              ('2026-06-03', 'AAPL', 'SPLIT', 4, NULL, NULL, NULL, NULL),
              ('2026-06-04', 'AAPL', 'SELL', 100, 37.50, 0, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-06-01', 150),
              ('AAPL', '2026-06-02', 150),
              ('AAPL', '2026-06-03', 37.50),
              ('AAPL', '2026-06-04', 37.50)
          `);

          const asOf = "2026-06-04";

          const [fifo] = await tx.unsafe(
            `SELECT * FROM portfolio_fifo_metrics_sql($1)`,
            [asOf],
          ) as any[];

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1)`,
            [asOf],
          ) as any[];

          const aaplRow = allocation.find((r: any) => r.asset === "AAPL");
          expect(aaplRow).toBeDefined();
          expect(aaplRow.net_quantity).toBe(300);

          const costBasis = Number(fifo.cost_basis);
          const expectedBasis = 300 * (150 / 4);
          expect(costBasis).toBeCloseTo(expectedBasis, 2);

          const realizedGain = Number(fifo.realized_gain);
          const expectedGain = (100 * 37.50) - (100 * (150 / 4));
          expect(realizedGain).toBeCloseTo(expectedGain, 2);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "reverse split: 1:10 on 100 shares @ $10 → 10 shares @ $100 unit cost",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-06-01', 'USD', 'DEPOSIT', 1000, NULL, 0, 'USD', NULL),
              ('2026-06-02', 'XYZ', 'BUY', 100, 10, 0, 'USD', NULL),
              ('2026-06-03', 'XYZ', 'SPLIT', 0.1, NULL, NULL, NULL, NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('XYZ', '2026-06-01', 10),
              ('XYZ', '2026-06-02', 10),
              ('XYZ', '2026-06-03', 100)
          `);

          const asOf = "2026-06-03";

          const [fifo] = await tx.unsafe(
            `SELECT * FROM portfolio_fifo_metrics_sql($1)`,
            [asOf],
          ) as any[];

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1)`,
            [asOf],
          ) as any[];

          const xyzRow = allocation.find((r: any) => r.asset === "XYZ");
          expect(xyzRow).toBeDefined();
          expect(xyzRow.net_quantity).toBeCloseTo(10, 6);

          const costBasis = Number(fifo.cost_basis);
          expect(costBasis).toBe(1000);

          const realizedGain = Number(fifo.realized_gain);
          expect(realizedGain).toBe(0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "SPLIT has no cash impact",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-06-01', 'USD', 'DEPOSIT', 10000, NULL, 0, 'USD', NULL),
              ('2026-06-02', 'AAPL', 'BUY', 100, 100, 0, 'USD', NULL)
          `);

          const cashBefore = await tx.unsafe(
            `SELECT * FROM portfolio_cash_sql('2026-06-02')`,
          ) as any[];

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES ('2026-06-03', 'AAPL', 'SPLIT', 2, NULL, NULL, NULL, NULL)
          `);

          const cashAfter = await tx.unsafe(
            `SELECT * FROM portfolio_cash_sql('2026-06-03')`,
          ) as any[];

          const beforeTotal = cashBefore.reduce(
            (sum: number, r: any) => sum + Number(r.usd_value),
            0,
          );
          const afterTotal = cashAfter.reduce(
            (sum: number, r: any) => sum + Number(r.usd_value),
            0,
          );

          expect(beforeTotal).toBeCloseTo(afterTotal, 2);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "no regression for non-split portfolios",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-06-01', 'USD', 'DEPOSIT', 10000, NULL, 0, 'USD', NULL),
              ('2026-06-02', 'AAPL', 'BUY', 10, 150, 5, 'USD', NULL),
              ('2026-06-03', 'MSFT', 'BUY', 20, 300, 5, 'USD', NULL),
              ('2026-06-04', 'AAPL', 'SELL', 5, 160, 2, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-06-01', 150),
              ('AAPL', '2026-06-02', 150),
              ('AAPL', '2026-06-03', 155),
              ('AAPL', '2026-06-04', 160),
              ('MSFT', '2026-06-03', 300),
              ('MSFT', '2026-06-04', 310)
          `);

          const [fifo] = await tx.unsafe(
            `SELECT * FROM portfolio_fifo_metrics_sql('2026-06-04')`,
          ) as any[];

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql('2026-06-04')`,
          ) as any[];

          const aaplRow = allocation.find((r: any) => r.asset === "AAPL");
          expect(aaplRow).toBeDefined();
          expect(aaplRow.net_quantity).toBe(5);

          const msftRow = allocation.find((r: any) => r.asset === "MSFT");
          expect(msftRow).toBeDefined();
          expect(msftRow.net_quantity).toBe(20);

          const realizedGain = Number(fifo.realized_gain);
          const expectedRealized = (5 * 160 - 2) - (5 * ((10 * 150 + 5) / 10));
          expect(realizedGain).toBeCloseTo(expectedRealized, 2);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "straddle: BUY 10, SPLIT 2, BUY 10 → allocation net 30 (order-aware, old bug gives 40)",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-06-01', 'USD', 'DEPOSIT', 5000, NULL, 0, 'USD', NULL),
              ('2026-06-02', 'AAPL', 'BUY', 10, 100, 0, 'USD', NULL),
              ('2026-06-03', 'AAPL', 'SPLIT', 2, NULL, NULL, NULL, NULL),
              ('2026-06-04', 'AAPL', 'BUY', 10, 200, 0, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-06-02', 100),
              ('AAPL', '2026-06-03', 50),
              ('AAPL', '2026-06-04', 200)
          `);

          const asOf = "2026-06-04";

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1)`,
            [asOf],
          ) as any[];

          const aaplRow = allocation.find((r: any) => r.asset === "AAPL");
          expect(aaplRow).toBeDefined();
          expect(aaplRow.net_quantity).toBe(30);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "SELL after SPLIT: allocation net_quantity matches FIFO (the #216 bug repro)",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-06-01', 'USD', 'DEPOSIT', 15000, NULL, 0, 'USD', NULL),
              ('2026-06-02', 'AAPL', 'BUY', 100, 150, 0, 'USD', NULL),
              ('2026-06-03', 'AAPL', 'SPLIT', 4, NULL, NULL, NULL, NULL),
              ('2026-06-04', 'AAPL', 'SELL', 100, 50, 0, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-06-01', 150),
              ('AAPL', '2026-06-02', 150),
              ('AAPL', '2026-06-03', 37.50),
              ('AAPL', '2026-06-04', 50)
          `);

          const asOf = "2026-06-04";

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1)`,
            [asOf],
          ) as any[];

          const aaplRow = allocation.find((r: any) => r.asset === "AAPL");
          expect(aaplRow).toBeDefined();
          expect(aaplRow.net_quantity).toBe(300);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "#87 invariant: status.portfolio_value ≈ SUM(allocation.value_usd) for post-split fixture",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(`
            CREATE TEMP TABLE transactions (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              date DATE NOT NULL,
              asset VARCHAR NOT NULL,
              action VARCHAR NOT NULL,
              quantity DOUBLE PRECISION NOT NULL,
              asset_type VARCHAR,
              price DOUBLE PRECISION,
              currency VARCHAR,
              fees DOUBLE PRECISION,
              fee_currency VARCHAR,
              exchange VARCHAR,
              data_source VARCHAR,
              account VARCHAR,
              exchange_group_id TEXT,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            CREATE TEMP TABLE prices (
              date DATE NOT NULL,
              ticker VARCHAR NOT NULL,
              price DOUBLE PRECISION NOT NULL,
              PRIMARY KEY (date, ticker)
            ) ON COMMIT DROP
          `);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency)
            VALUES
              ('2026-06-01', 'USD', 'DEPOSIT', 20000, NULL, 0, 'USD', NULL),
              ('2026-06-02', 'AAPL', 'BUY', 100, 150, 5, 'USD', NULL),
              ('2026-06-03', 'AAPL', 'SPLIT', 4, NULL, NULL, NULL, NULL),
              ('2026-06-04', 'AAPL', 'SELL', 100, 50, 2, 'USD', NULL),
              ('2026-06-05', 'MSFT', 'BUY', 10, 300, 3, 'USD', NULL)
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-06-01', 150),
              ('AAPL', '2026-06-02', 150),
              ('AAPL', '2026-06-03', 37.50),
              ('AAPL', '2026-06-04', 50),
              ('AAPL', '2026-06-05', 52),
              ('MSFT', '2026-06-05', 300)
          `);

          const asOf = "2026-06-05";

          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [asOf],
          ) as any[];

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1)`,
            [asOf],
          ) as any[];

          const allocTotal = allocation.reduce(
            (sum: number, r: any) => sum + Number(r.value_usd),
            0,
          );

          const statusValue = Number(status.portfolio_value);
          const tolerance = 0.02;

          expect(statusValue).toBeCloseTo(allocTotal, 2);
          expect(Math.abs(statusValue - allocTotal)).toBeLessThan(tolerance);
          expect(statusValue).toBeGreaterThan(0);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );
});
