import { describe, expect, test } from "bun:test";
import { SQL } from "bun";

const DB_URL = process.env.PORTFOLIO_DB_URL;
const MAYBE_SKIP = DB_URL ? describe : describe.skip;

const TEMP_TABLES = `
  CREATE TEMP TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    asset VARCHAR NOT NULL,
    action VARCHAR NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    asset_type VARCHAR,
    price DOUBLE PRECISION,
    currency VARCHAR,
    fees DOUBLE PRECISION,
    fee_currency VARCHAR,
    exchange VARCHAR,
    data_source VARCHAR,
    account VARCHAR,
    exchange_group_id TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
  ) ON COMMIT DROP;

  CREATE TEMP TABLE prices (
    date DATE NOT NULL,
    ticker VARCHAR NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (date, ticker)
  ) ON COMMIT DROP;
`;

MAYBE_SKIP("integration: stablecoin cash support (#211)", () => {
  test(
    "hand-calc fixture: USDT 500 + USDC 250 → separate CASH USDT/CASH USDC buckets, 1:1 value",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-06-01', 'USDT', 'DEPOSIT', 500,  NULL, 0, 'USD', NULL, 'binance'),
              ('2026-06-02', 'USDC', 'DEPOSIT', 250,  NULL, 0, 'USD', NULL, 'coinbase')
          `);

          const asOf = "2026-06-02";

          const cash = await tx.unsafe(
            `SELECT * FROM portfolio_cash_sql($1) ORDER BY cash_key`,
            [asOf],
          ) as any[];

          const totalUsd = cash.reduce((s: number, r: any) => s + Number(r.usd_value), 0);

          // Two separate buckets
          expect(cash.length).toBe(2);

          const usdt = cash.find((r: any) => r.cash_key === "USDT");
          const usdc = cash.find((r: any) => r.cash_key === "USDC");

          expect(usdt).toBeDefined();
          expect(usdc).toBeDefined();

          // USDT bucket
          expect(usdt.display_bucket).toBe("CASH USDT");
          expect(usdt.currency).toBe("USDT");
          expect(Number(usdt.balance)).toBeCloseTo(500, 2);
          expect(Number(usdt.usd_value)).toBeCloseTo(500, 2);

          // USDC bucket
          expect(usdc.display_bucket).toBe("CASH USDC");
          expect(usdc.currency).toBe("USDC");
          expect(Number(usdc.balance)).toBeCloseTo(250, 2);
          expect(Number(usdc.usd_value)).toBeCloseTo(250, 2);

          // Total USD
          expect(totalUsd).toBeCloseTo(750, 2);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "regression: portfolio with zero stablecoins yields identical outputs (no new buckets)",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-01-01', 'USD',  'DEPOSIT', 10000, NULL, 0, 'USD', NULL, 'bank'),
              ('2026-01-02', 'AAPL', 'BUY',     10,    150, 5,  'USD', NULL, 'nasdaq')
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-01-02', 150),
              ('AAPL', '2026-01-03', 155)
          `);

          const asOf = "2026-01-03";

          const cash = await tx.unsafe(
            `SELECT * FROM portfolio_cash_sql($1) ORDER BY cash_key`,
            [asOf],
          ) as any[];

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1) ORDER BY asset`,
            [asOf],
          ) as any[];

          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [asOf],
          ) as any[];

          // Cash buckets: only USD (no phantom stablecoin buckets)
          const cashKeys = cash.map((r: any) => r.cash_key);
          expect(cashKeys).not.toContain("USDT");
          expect(cashKeys).not.toContain("USDC");
          expect(cashKeys).toContain("USD");

          // Allocation: only AAPL + USD cash
          const allocAssets = allocation.map((r: any) => r.asset);
          expect(allocAssets).toContain("AAPL");
          expect(allocAssets).toContain("USD");
          expect(allocAssets).not.toContain("USDT");

          // No stablecoin asset_types in allocation
          const allocTypes = allocation.map((r: any) => r.asset_type);
          expect(allocTypes).not.toContain("cash_stable");

          // Status portfolio value = starting cash 10000 - BUY cost 1505 = 8495 cash
          // + 10*155 market = 1550 = total 10045
          // Hand calc: cash = 10000 - (10*150 + 5) = 10000 - 1505 = 8495
          // AAPL market: 10 * 155 = 1550
          // Total: 8495 + 1550 = 10045
          expect(Number(status.portfolio_value)).toBeCloseTo(10045, 1);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "valuation path: portfolio_value / status / summary reflect stablecoin at 1:1",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-06-01', 'USD',  'DEPOSIT', 1000, NULL, 0, 'USD', NULL, 'bank'),
              ('2026-06-02', 'USDT', 'DEPOSIT', 500,  NULL, 0, 'USD', NULL, 'binance')
          `);

          const asOf = "2026-06-02";

          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [asOf],
          ) as any[];

          const [summary] = await tx.unsafe(
            `SELECT * FROM portfolio_summary_sql($1)`,
            [asOf],
          ) as any[];

          // Hand calc: 1000 USD + 500 USDT = 1500 total value (both 1:1)
          expect(Number(status.portfolio_value)).toBeCloseTo(1500, 2);
          expect(Number(summary.portfolio_value_usd)).toBeCloseTo(1500, 2);

          // total_invested = deposits (1500) - withdrawals (0) = 1500
          expect(Number(status.total_invested)).toBeCloseTo(1500, 2);

          // total_gain = portfolio_value - total_invested = 0 (no gain on 1:1 cash)
          expect(Number(status.total_gain)).toBeCloseTo(0, 2);

          // Deposits: 1000 + 500 = 1500
          expect(Number(status.deposits)).toBeCloseTo(1500, 2);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "no price required: verify_prices / needs-fetch does NOT list stablecoins",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-06-01', 'USDT', 'DEPOSIT', 500, NULL, 0, 'USD', NULL, 'binance'),
              ('2026-06-01', 'DAI',  'DEPOSIT', 300, NULL, 0, 'USD', NULL, 'defi'),
              ('2026-06-02', 'AAPL', 'BUY',     5,   200, 0,  'USD', NULL, 'nasdaq')
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-06-02', 200)
          `);

          // discover_required_tickers_sql must not include stablecoins
          const tickers = await tx.unsafe(
            `SELECT * FROM discover_required_tickers_sql() ORDER BY ticker`,
          ) as any[];

          const tickerNames = tickers.map((r: any) => r.ticker);
          expect(tickerNames).not.toContain("USDT");
          expect(tickerNames).not.toContain("DAI");
          expect(tickerNames).not.toContain("USDT-USD");
          expect(tickerNames).not.toContain("DAI-USD");

          // get_required_price_checkpoints_sql must not include stablecoins
          const checkpoints = await tx.unsafe(
            `SELECT DISTINCT ticker FROM get_required_price_checkpoints_sql($1) ORDER BY ticker`,
            ["2026-06-02"],
          ) as any[];

          const cpTickers = checkpoints.map((r: any) => r.ticker);
          expect(cpTickers).not.toContain("USDT");
          expect(cpTickers).not.toContain("DAI");
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "allocation: stablecoin appears as cash-side row with asset_type=cash_stable",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-06-01', 'USD',  'DEPOSIT', 2000, NULL, 0, 'USD', NULL, 'bank'),
              ('2026-06-02', 'USDC', 'DEPOSIT', 500,  NULL, 0, 'USD', NULL, 'coinbase'),
              ('2026-06-03', 'AAPL', 'BUY',     5,   200,  0, 'USD', NULL, 'nasdaq')
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL', '2026-06-03', 200)
          `);

          const asOf = "2026-06-03";

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1) ORDER BY asset`,
            [asOf],
          ) as any[];

          // Should have 3 rows: USD (cash_base), USDC (cash_stable), AAPL (stock_usd)
          expect(allocation.length).toBe(3);

          const usdc = allocation.find((r: any) => r.asset === "USDC");
          expect(usdc).toBeDefined();
          expect(usdc.asset_type).toBe("cash_stable");
          expect(usdc.asset_kind).toBe("cash");

          // USDC value = 500 (1:1), should be a cash-side row
          expect(Number(usdc.value_usd)).toBeCloseTo(500, 2);

          // Verify USDC is NOT in the non-cash side (it's cash-like)
          const nonCashAssets = allocation
            .filter((r: any) => r.asset_type !== "cash_base" && r.asset_type !== "cash_fx" && r.asset_type !== "cash_stable")
            .map((r: any) => r.asset);
          expect(nonCashAssets).not.toContain("USDC");
          expect(nonCashAssets).toContain("AAPL");

          // detect_asset_kind returns 'cash'
          const [kindRow] = await tx.unsafe(
            `SELECT detect_asset_kind($1) AS kind`,
            ["USDC"],
          ) as any[];
          expect(kindRow.kind).toBe("cash");
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "is_stablecoin_sql returns correct results",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          // True for all 9
          const coins = ["USDT", "USDC", "DAI", "TUSD", "USDP", "FDUSD", "PYUSD", "USDE", "GUSD"];
          for (const c of coins) {
            const [r] = await tx.unsafe(`SELECT is_stablecoin_sql($1) AS ok`, [c]) as any[];
            expect(r.ok).toBe(true);
            const [rl] = await tx.unsafe(`SELECT is_stablecoin_sql($1) AS ok`, [c.toLowerCase()]) as any[];
            expect(rl.ok).toBe(true);
          }

          // False for non-stablecoins
          for (const c of ["USD", "BTC-USD", "EURUSD=X", "AAPL", "SPYM"]) {
            const [r] = await tx.unsafe(`SELECT is_stablecoin_sql($1) AS ok`, [c]) as any[];
            expect(r.ok).toBe(false);
          }
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "fee_currency ticker: stablecoin fee_currency uses stablecoin itself as cash_key",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          // fee_currency_ticker_sql should return the stablecoin symbol itself
          const [r] = await tx.unsafe(`SELECT fee_currency_ticker_sql($1) AS tkr`, ["USDT"]) as any[];
          expect(r.tkr).toBe("USDT");
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "CASH <stablecoin> literal: DEPOSIT CASH USDT 300 → correct bucket, 1:1 value, no price required",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-06-01', 'USD',       'DEPOSIT', 1000, NULL, 0, 'USD', NULL, 'bank'),
              ('2026-06-02', 'CASH USDT', 'DEPOSIT', 300,  NULL, 0, 'USD', NULL, 'binance'),
              ('2026-06-03', 'CASH USDC', 'DEPOSIT', 200,  NULL, 0, 'USD', NULL, 'coinbase')
          `);

          const asOf = "2026-06-03";

          const cash = await tx.unsafe(
            `SELECT * FROM portfolio_cash_sql($1) ORDER BY cash_key`,
            [asOf],
          ) as any[];

          // CASH USDT bucket
          const usdt = cash.find((r: any) => r.cash_key === "USDT");
          expect(usdt).toBeDefined();
          expect(usdt.display_bucket).toBe("CASH USDT");
          expect(Number(usdt.balance)).toBeCloseTo(300, 2);
          expect(Number(usdt.usd_value)).toBeCloseTo(300, 2);

          // CASH USDC bucket
          const usdc = cash.find((r: any) => r.cash_key === "USDC");
          expect(usdc).toBeDefined();
          expect(usdc.display_bucket).toBe("CASH USDC");
          expect(Number(usdc.balance)).toBeCloseTo(200, 2);
          expect(Number(usdc.usd_value)).toBeCloseTo(200, 2);

          // Total cash: 1000 USD + 300 USDT + 200 USDC = 1500
          const totalUsd = cash.reduce((s: number, r: any) => s + Number(r.usd_value), 0);
          expect(totalUsd).toBeCloseTo(1500, 2);

          // Not listed in required tickers
          const tickers = await tx.unsafe(
            `SELECT * FROM discover_required_tickers_sql() ORDER BY ticker`,
          ) as any[];
          const tickerNames = tickers.map((r: any) => r.ticker);
          expect(tickerNames).not.toContain("USDT");
          expect(tickerNames).not.toContain("USDC");
          expect(tickerNames).not.toContain("CASH USDT");
          expect(tickerNames).not.toContain("CASH USDC");
          expect(tickerNames).not.toContain("CASH USDT-USD");
          expect(tickerNames).not.toContain("CASH USDC-USD");

          // Not in required price checkpoints
          const checkpoints = await tx.unsafe(
            `SELECT DISTINCT ticker FROM get_required_price_checkpoints_sql($1) ORDER BY ticker`,
            [asOf],
          ) as any[];
          const cpTickers = checkpoints.map((r: any) => r.ticker);
          expect(cpTickers).not.toContain("USDT");
          expect(cpTickers).not.toContain("CASH USDT");
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "exchange USD ↔ CASH USDT round-trips to the correct bucket",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-06-01', 'USD',       'DEPOSIT',    1000, NULL, 0, 'USD', NULL, 'bank'),
              ('2026-06-02', 'CASH USDT', 'DEPOSIT',     500, NULL, 0, 'USD', NULL, 'binance')
          `);

          const asOf = "2026-06-02";

          const cash = await tx.unsafe(
            `SELECT * FROM portfolio_cash_sql($1) ORDER BY cash_key`,
            [asOf],
          ) as any[];

          const usd = cash.find((r: any) => r.cash_key === "USD");
          const usdt = cash.find((r: any) => r.cash_key === "USDT");

          expect(usd).toBeDefined();
          expect(usdt).toBeDefined();
          expect(Number(usd.balance)).toBeCloseTo(1000, 2);
          expect(Number(usdt.balance)).toBeCloseTo(500, 2);
          expect(Number(usdt.usd_value)).toBeCloseTo(500, 2);
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );

  test(
    "regression: no harm to non-stablecoin portfolios — identical values with/without stablecoin path",
    async () => {
      const sql = new SQL(DB_URL!, { max: 1 });
      try {
        await sql.begin(async (tx: any) => {
          await tx.unsafe(TEMP_TABLES);

          // Fixture: USD cash, FX cash bucket, stock, crypto — NO stablecoins
          await tx.unsafe(`
            INSERT INTO transactions (date, asset, action, quantity, price, fees, currency, fee_currency, exchange)
            VALUES
              ('2026-01-15', 'USD',      'DEPOSIT', 20000, NULL, 0,    'USD', NULL, 'bank'),
              ('2026-01-16', 'GBP',      'DEPOSIT', 1000,  NULL, 0,    'USD', NULL, 'bank'),
              ('2026-01-17', 'AAPL',     'BUY',     10,    150,  5,    'USD', NULL, 'nasdaq'),
              ('2026-01-18', 'BTC-USD',  'BUY',     0.5,   40000, 2.50, 'USD', NULL, 'coinbase'),
              ('2026-01-19', 'SAP.DE',   'BUY',     5,     120,  15,   'EUR', NULL, 'xetra')
          `);

          await tx.unsafe(`
            INSERT INTO prices (ticker, date, price)
            VALUES
              ('AAPL',     '2026-01-17', 150),
              ('AAPL',     '2026-01-18', 155),
              ('AAPL',     '2026-01-19', 160),
              ('BTC-USD',  '2026-01-18', 40000),
              ('BTC-USD',  '2026-01-19', 42000),
              ('SAP.DE',   '2026-01-19', 120),
              ('GBPUSD=X', '2026-01-19', 1.30),
              ('EURUSD=X', '2026-01-19', 1.10)
          `);

          const asOf = "2026-01-19";

          const cash = await tx.unsafe(
            `SELECT * FROM portfolio_cash_sql($1) ORDER BY cash_key`,
            [asOf],
          ) as any[];

          const allocation = await tx.unsafe(
            `SELECT * FROM portfolio_allocation_sql($1) ORDER BY asset`,
            [asOf],
          ) as any[];

          const [status] = await tx.unsafe(
            `SELECT * FROM portfolio_status_sql($1)`,
            [asOf],
          ) as any[];

          // Hand-calculated values:
          // Starting USD: 20000
          // BUY AAPL: 10*150 + 5 = -1505 USD
          // BUY BTC-USD: 0.5*40000 + 2.50 = -20002.50 USD
          // BUY SAP.DE: 5*120 + 15 = -615 EUR (EUR bucket, not USD)
          // USD cash: 20000 - 1505 - 20002.50 = -1507.50
          // EUR cash (EURUSD=X): -615 EUR → FX at 1.10 = -676.50 USD
          // GBP cash: 1000 GBP → FX at 1.30 = 1300 USD
          // AAPL market: 10 * 160 = 1600
          // BTC-USD market: 0.5 * 42000 = 21000
          // SAP.DE market: 5 * 120 * 1.10 = 660
          // Total portfolio: -1507.50 - 676.50 + 1300 + 1600 + 21000 + 660 = 22376

          // Cash assertions
          const usdCash = cash.find((r: any) => r.cash_key === "USD");
          const gbpCash = cash.find((r: any) => r.cash_key === "GBPUSD=X");
          const eurCash = cash.find((r: any) => r.cash_key === "EURUSD=X");
          expect(usdCash).toBeDefined();
          expect(gbpCash).toBeDefined();
          expect(eurCash).toBeDefined();
          expect(Number(usdCash.balance)).toBeCloseTo(-1507.5, 1);
          expect(Number(gbpCash.usd_value)).toBeCloseTo(1300, 1);
          expect(Number(eurCash.balance)).toBeCloseTo(-615, 1);

          // No stablecoin buckets or asset_types
          const cashKeys = cash.map((r: any) => r.cash_key);
          for (const key of cashKeys) {
            // Verify none of these keys are stablecoins
            const [isStable] = await tx.unsafe(`SELECT is_stablecoin_sql($1) AS ok`, [key]) as any[];
            expect(isStable.ok).toBe(false);
          }
          const allocTypes = allocation.map((r: any) => r.asset_type);
          expect(allocTypes).not.toContain("cash_stable");

          // Total value
          expect(Number(status.portfolio_value)).toBeCloseTo(22376, 0);

          // Allocation total matches status
          const allocTotal = allocation.reduce(
            (sum: number, r: any) => sum + Number(r.value_usd),
            0,
          );
          expect(allocTotal).toBeCloseTo(Number(status.portfolio_value), 1);

          // Allocation contains expected assets
          const allocAssets = allocation.map((r: any) => r.asset);
          expect(allocAssets).toContain("AAPL");
          expect(allocAssets).toContain("BTC-USD");
          expect(allocAssets).toContain("SAP.DE");
        });
      } finally {
        await sql.end();
      }
    },
    { timeout: 15000 },
  );
});
