-- Migration: add scheduled_job_log table for pg_cron job audit trail.
-- Idempotent: safe to run multiple times on an existing DB.
-- See docs/pg-cron.md for pg_cron extension setup and lifecycle documentation.

CREATE TABLE IF NOT EXISTS scheduled_job_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'running',
    rows_affected INTEGER,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_scheduled_job_log_job_name ON scheduled_job_log (job_name);
CREATE INDEX IF NOT EXISTS idx_scheduled_job_log_started ON scheduled_job_log (started_at DESC);
