-- Portfolio database schema for PostgreSQL
-- Idempotent schema definition

-- Transactions table: core transaction log
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    asset VARCHAR NOT NULL,
    action VARCHAR NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    asset_type VARCHAR,
    price DOUBLE PRECISION,
    currency VARCHAR,
    fees DOUBLE PRECISION,
    fee_currency VARCHAR,
    exchange VARCHAR,
    data_source VARCHAR,
    account VARCHAR,
    exchange_group_id TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Prices table: historical price data for tickers
CREATE TABLE IF NOT EXISTS prices (
    date DATE NOT NULL,
    ticker VARCHAR NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (date, ticker)
);

CREATE INDEX IF NOT EXISTS idx_prices_ticker ON prices (ticker);

-- Daily returns: portfolio valuation and return calculations
CREATE TABLE IF NOT EXISTS daily_returns (
    date DATE PRIMARY KEY,
    portfolio_value DOUBLE PRECISION NOT NULL,
    portfolio_daily_return DOUBLE PRECISION,
    investment_return DOUBLE PRECISION,
    cash_flow_impact DOUBLE PRECISION,
    adjusted_base DOUBLE PRECISION
);

-- Refresh log: audit trail of price/data refreshes
CREATE TABLE IF NOT EXISTS refresh_log (
    refresh_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refresh_date DATE NOT NULL,
    refresh_type VARCHAR NOT NULL,
    rows_affected INTEGER,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Recalculation cache: optimization for change detection
CREATE TABLE IF NOT EXISTS recalc_cache (
    cache_key VARCHAR PRIMARY KEY,
    last_calc_date DATE NOT NULL,
    transaction_count INTEGER NOT NULL,
    prices_hash VARCHAR,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Service state: explicit state for freshness tracking
CREATE TABLE IF NOT EXISTS service_state (
    state_key VARCHAR PRIMARY KEY,
    state_value VARCHAR,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Repair log: audit trail of price repairs
CREATE TABLE IF NOT EXISTS repair_log (
    repair_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR NOT NULL,
    start_date DATE,
    end_date DATE,
    status VARCHAR NOT NULL,
    rows_loaded INTEGER DEFAULT 0,
    message VARCHAR,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Asset metadata: per-ticker metadata from Yahoo Finance (quoteType, sector, industry, etc.)
CREATE TABLE IF NOT EXISTS asset_metadata (
    ticker VARCHAR PRIMARY KEY,
    yahoo_quote_type VARCHAR,
    yahoo_type_disp VARCHAR,
    yahoo_short_name VARCHAR,
    yahoo_long_name VARCHAR,
    currency VARCHAR,
    exchange VARCHAR,
    asset_kind VARCHAR,
    sector VARCHAR,
    industry VARCHAR,
    region VARCHAR,
    sector_weights JSONB,
    source VARCHAR,
    fetched_at TIMESTAMPTZ DEFAULT NOW()
);
